### PR TITLE
Update AddNewContent page based on Delph feedback

### LINKED ISSUE #1545: Enhancement: Add Content page (Delph suggestions)
This ticket is about new suggestions for the "add content" page : https://fairsharing.org/new

Thanks a lot Hossein for the new page, what you have done is much clearer :)

I have a few suggestions to make it perfect. This page is very important for us because we lose a lot of time rejecting submissions that are datasets and explaining to the users why we reject their submission:

- **Header** 
Why not put the same header as all the other pages to make the website more consistent? 
Capture d’écran 2022-02-17 à 17 41 13

- **Columns** 
I saw that on the home page, you used this formalism for columns, with a nice effect when you move the mouse over it. Maybe we can use it again? 
Capture d’écran 2022-02-17 à 17 44 19

Is it possible to arrange the columns differently? 
Here are 3 suggestions, tell me what you think, I prefer the 1st proposal.
* 4 columns on 1 line
Capture d’écran 2022-02-17 à 17 46 49

* 3 columns on 1 line / 1 column on another line (central)
Capture d’écran 2022-02-17 à 17 47 20

* 2 columns on 1 line / 2 column on another line 
Capture d’écran 2022-02-17 à 17 48 06

Is it possible to remove the "justify" for the text under standard, database, collection and policy ? maybe center will be better ? 

**- Size of the titles**
It seems that the titles "What to add" ; "No datasets, please" ; "Get Started!" have not the same size (+ 1 is in bold). I think that those titles should use the same css (h2?).

**- Colours** 
This one is difficult... I'm sorry, I gave you the wrong colour for the "please no dataset" box when I gave you my drawing, I did it quickly on ppt, I didn't have the graphic palette available. I think that this box should take a colour from the graphic palette. Maybe the red or the orange? I'll let you choose, you're the expert! 
Same for the blue box, it's a little bit aggressive, I would put a light grey. You can try to make a band, 
Not sure it's necessary to highlight some text in blue. Maybe just in bold, or the color used for the links in the css is sufficient.

It might look something like this :
Capture d’écran 2022-02-17 à 18 05 30

What do you think of it ?

### PR DESCRIPTION
**Pull request by hoseinmirian**
screenshot for @delphinedauga to review in case preview is broken:

image

### CODE REVIEW

**Comment by knirirr** [comment]
Looks nice overall, and the build is working for me.
But, even on a large monitor I'm seeing the "collections" element on a new line; if the four registry elements could be made to fit on one I think it would be preferable.

**Comment by hoseinmirian** [comment]
> Looks nice overall, and the build is working for me. But, even on a large monitor I'm seeing the "collections" element on a new line; if the four registry elements could be made to fit on one I think it would be preferable.

that's very true, fixed now by last commit. 

image

**Comment by hoseinmirian** [comment]
@knirirr 

icons were missing surprisingly! added

image

**Review by delphinedauga — COMMENTED** [review]
Thanks Hossein ! It's very nice ! I like it !
2 points : 

- Can you remove the first paragraph ? :
pic

- And put the following text in the "header" (paragraph on the blue image) instead ? this is the text that is currently on the page, which was validated by Ally. Sorry for the confusion.
Also, is it possible to keep the links to the "FAIRsharing Team" and "claim and edit existing record(s)" texts in the header? 
Thanks !

pic2

"The [FAIRsharing Team](https://fairsharing.org/communities#governance) curates and integrates descriptions of community resources, such as standards and databases, progressively linking both to policies. However, we know that the maintainers of these resources know best. So if you find that the resource you lead or work for has an incomplete or incorrect description, you can either [claim and edit existing record(s)](https://fairsharing.gitbook.io/fairsharing/#claiming-a-record) or continue reading to get started with a new record submission, if your resource is missing."

**Review by knirirr — APPROVED** [review]

**Comment by hoseinmirian** [comment]
@delphinedauga 

image

**Review by delphinedauga — APPROVED** [review]
Super cool ! I approve !

**Pull request merged**
