### PR TITLE
Aligned registry type and abbreviation in cardStack

### LINKED ISSUE #1210: Abbrevation and comments should be centered vertically
image

### PR DESCRIPTION
**Pull request by hoseinmirian**
now the abbreviation and registry type is aligned center vertically. please check RecordsCardStack

### CODE REVIEW

**Comment by knirirr** [comment]
The Netlify build I'm looking at doesn't have centered abbreviations similar to what's shown in the original ticket - they're aligned to the left:

Screenshot 2021-10-14 at 15 56 12

**Comment by hoseinmirian** [comment]
> The Netlify build I'm looking at doesn't have centered abbreviations similar to what's shown in the original ticket - they're aligned to the left:
> 
> Screenshot 2021-10-14 at 15 56 12

that is correct due to I did center abbreviation but it looked bizarre so I decided to keep it on left. it looks more aligned this way.

**Comment by knirirr** [comment]
The requirements in the ticket state that they should be central, though:
https://github.com/FAIRsharing/fairsharing.github.io/issues/1210

**Comment by hoseinmirian** [comment]
abbreviation become center in search cards. 
image

**Review by knirirr — APPROVED** [review]

**Pull request merged**
