### PR TITLE
Fix bug with status color in editor

### LINKED ISSUE #1451: Deprecated icon colour is not the new standard "maroon" colour in edit interface
**Describe the bug**
Deprecated icon colour is not the new standard "maroon" colour in the General Information tab of the edit interface - it has remained the old grey colour.

**To Reproduce**
1. Go to any record, and open the edit interface
2. Click 'Status' pulldown
3. See error

**Expected behavior**
The colours should match the default status colours of the rest of the site.

**Screenshots**
deprecated-colour

**Operating system and browser version**
Ubuntu / Firefox

### PR DESCRIPTION
**Pull request by hoseinmirian**
bug in regard to status color in editor is fixed.

### CODE REVIEW

**Comment by allysonlister** [comment]
Sorry I still cannot see the build, either with or without the vpn turned on (I know we don't need the vpn, but I was just double checking). It just continues to show the "maintenance mode" page.

**Comment by hoseinmirian** [comment]
> Sorry I still cannot see the build, either with or without the vpn turned on (I know we don't need the vpn, but I was just double checking). It just continues to show the "maintenance mode" page.

for me again is working as expected:
image

**Comment by allysonlister** [comment]
It's clear that it isn't working for me, and is for you. I suggest you add this to the agenda for our Monday meeting, and we can bring it up and see if this particular behaviour is an issue at my end, or requires a ticket. Thanks!

**Comment by knirirr** [comment]
@allysonlister the development server is now accessible.

**Review by allysonlister — APPROVED** [review]
Thank you - looks good!

**Review by knirirr — APPROVED** [review]

**Pull request merged**
