### PR TITLE
Access point display changes 1653

### LINKED ISSUE #1817: Display Attributes and Conditions data
**Describe the bug**
Rows like Data Curation, Data Access Condition, Data Deposition Condition, Resource sustainability etc. within Attributes and Conditions section should be displayed if they have the data otherwise respective rows should be hidden

**To Reproduce**
1. Go to 'https://fairsharing.org/dryad'
2. Scroll to ```Attributes and Conditions``` block within ```DATA PROCESSES AND CONDITIONS```.
3. If any row like ```Resource sustainability``` does not have any data, that row should not be displayed
 

**Expected behavior**
image

**Actual behavior**
image

### PR DESCRIPTION
**Pull request by prakhyatox**
Ticket:
https://github.com/FAIRsharing/fairsharing.github.io/issues/1653

WDID:
Update the view for DataProcessAndCondition block
image

### CODE REVIEW

**Comment by prakhyatox** [comment]
@allysonlister Kindly review and let me know your feedback

**Comment by allysonlister** [comment]
What's there looks good, however the following features are missing from the mockup as outlined in our gitbook page:

* example URL and documentation URL are available to a number of these items (as described in the table [here](https://app.gitbook.com/o/-MchtBAOWXh2gO--zz7m/s/-MkSKpWh9NA-iywIqhP_/please-can-we/record-specific-specifications/update-additional-information-fields#how-they-should-change))

The following are described [here](https://app.gitbook.com/o/-MchtBAOWXh2gO--zz7m/s/-MkSKpWh9NA-iywIqhP_/please-can-we/record-specific-specifications/update-additional-information-fields#display-in-record-view):
* certification and community badges
* resource sustainability
* data versioning
* data contact information
* citation to related publications
* data access for pre-publication review

The mockup needs to include all new displays so I can evaluate them - thank you!!

**Comment by knirirr** [comment]
> The mockup needs to include all new displays so I can evaluate them - thank you!!

Please have a look at the Netlify build - I've added some placeholder information to a record here:

https://deploy-preview-1812--fairsharing.netlify.app/1120

N.B. I'm aware that items are also visible in the "additional information" section and I'll deal with that shortly. The same goes for example/documentation URLs. etc.

**Comment by allysonlister** [comment]
Thank you!

All of this looks great, very happy with it. Please let me know when I should have a final look once
* the final few items are moved from the additional information to the data processes and conditions, and
* the certification and community badge placeholder text is added so I can see how that looks.

**Comment by prakhyatox** [comment]
The Netlify build is ready to review with all the info

https://deploy-preview-1812--fairsharing.netlify.app/dryad

**Comment by allysonlister** [comment]
Thanks Prakhyat :)

Once the items in https://github.com/FAIRsharing/fairsharing.github.io/pull/1812#issuecomment-1234094239 have been added so I can have a final look, I'll review this.

**Comment by prakhyatox** [comment]
The items in https://github.com/FAIRsharing/fairsharing.github.io/pull/1812#issuecomment-1234094239 are already there in https://deploy-preview-1812--fairsharing.netlify.app/dryad

**Comment by allysonlister** [comment]
Thanks - I can see the community badge at the bottom now.

However, a number of items are still inside the Additional Information card when I've asked for them to be in the main data processes and conditions area as specified in gitbook

image
image

Thanks!

**Comment by prakhyatox** [comment]
Items are included as per gitbook. Please review and let me know the comments if any

https://deploy-preview-1812--fairsharing.netlify.app/dryad

**Comment by allysonlister** [comment]
Thank you. Gitbook had specified licences in the same "card" as the community badges, but I'll change that as I think we should leave them as you have them.

This is looking good. Now that I can see it all together, it looks odd for there to be card titles for licences and community badges and no titles for the other two cards. Therefore, please can you add "Processes" as the title for the card with the read/write items; and "Attributes and Conditions" as the title for the other untitled card.

I think that will finish this ticket - thanks for your patience!

**Comment by prakhyatox** [comment]
Updated as per the comments in https://github.com/FAIRsharing/fairsharing.github.io/pull/1812#issuecomment-1234399515

**Review by allysonlister — APPROVED** [review]
Fantastic, thanks!

**Review by knirirr — APPROVED** [review]

**Pull request merged**
