### PR TITLE
Doi download file

### LINKED ISSUE #1473: Comma substitution in DOI download file
See https://github.com/FAIRsharing/FAIRsharing-API/issues/424 for further details; record 950 is affected, so:

```json
{
	"357": {
		"id": 950,
		"name": "IUPAC-IUB Commission on Biochemical Nomenclature - Abbreviations and Symbols for Nucleic Acids, Polynucleotides and their Constituents",
		"createdAt": "2019-11-06T13:38:24Z",
		"updatedAt": "2021-11-24T13:15:43Z",
		"creator": {
			"id": 579,
			"username": "allysonlister"
		},
		"lastEditor": null
	}
}
```

Comes from the server but:

```
950|IUPAC-IUB Commission on Biochemical Nomenclature - Abbreviations and Symbols for Nucleic Acids Polynucleotides and their Constituents|2019-11-06 13:38:24 UTC|2021-11-24 13:15:43 UTC|allysonlister|
```

Is found in the file. This is presumably the cause of the new line mentioned.

### PR DESCRIPTION
**Pull request by knirirr**
This prevents commas in record names being turned into line breaks on the client when downloading the list of files needing a DOI from the curator page. 

https://github.com/FAIRsharing/fairsharing.github.io/issues/1473

### CODE REVIEW

**Comment by allysonlister** [comment]
I'm really sorry, but the downloaded file obtained from the curation dashboard appears empty. Am I doing something wrong? https://deploy-preview-1476--fairsharing.netlify.app/curator

**Comment by knirirr** [comment]
The job took much longer than it should but has now finished. These data will not match beta as the dev server's data are older.

```
2.7.3 :001 > FairsharingRecord.where(needs_doi: true).count
 => 404 
```

**Review by ramGranell — APPROVED** [review]
It seems to work properly and I check the record with ID 950 and seems to be correct

**Review by allysonlister — APPROVED** [review]
Looks great, thank you! Will wait for it to be merged before I use it "for real". Thanks!

**Pull request merged**
