### PR TITLE
Organisations simple search 1731

### PR DESCRIPTION
**Pull request by prakhyatox**
Ticket: https://github.com/FAIRsharing/fairsharing.github.io/issues/1731

Description:

1. Added new page i.e. `Organisations List` where all the organisations are listed
2. Added unit test case for the new view as mentioned in point 1
3. Added the new menu button `Organisations` for navigation
4. 
image

5. Dividing main menu in in two levels of menu 
6. Highlighting `Standards`, `Databases` , `Policies` menu items to as primary items

image

image

7. Updated Login button background to `green` once user is logged in
image

8. Added script `"lint:fix": "vue-cli-service lint --fix"` for fixing linting issues in package.json

Dependency PR:
There is no dependent PR

### CODE REVIEW

**Review by knirirr — CHANGES_REQUESTED** [review]
This looks good - thanks.
Would you mind adding one thing before merging, though: A link to our own page for an organisation, which should be /organisations/:id.
This could perhaps be a small "view details" button or a link (e.g. on the organisation name) - I'll leave the details to you.

**Comment by prakhyatox** [comment]
> This looks good - thanks. Would you mind adding one thing before merging, though: A link to our own page for an organisation, which should be /organisations/:id. This could perhaps be a small "view details" button or a link (e.g. on the organisation name) - I'll leave the details to you.

Fixed

**Comment by terazus** [comment]
Small question: why is the URL /organisationsList and not /organisations ?

**Comment by prakhyatox** [comment]
> Small question: why is the URL /organisationsList and not /organisations ?

/organisationsList to be in sync with /usersList. 

But have changed to /organisations now.
Fixed

**Review by knirirr — APPROVED** [review]

**Pull request merged**
