### PR TITLE
Apply Delph feedback

### PR DESCRIPTION
**Pull request by hoseinmirian**

### CODE REVIEW

**Review by delphinedauga — APPROVED** [review]
Ok !

**Review by knirirr — CHANGES_REQUESTED** [review]
Unfortunately, though this fixes the immediate problem, legacy.fairsharing.org will eventually disappear and so this image will become unavailable.
So, it will need to be moved into the new application. 
Good that it's been spotted before we turned legacy off, though.

**Comment by hoseinmirian** [comment]
ok I download the file and push it in our public/assets ? @knirirr

**Comment by knirirr** [comment]
That's probably the best place for it, yes.

**Review by knirirr — APPROVED** [review]

**Pull request merged**
