### PR TITLE
User error hide 2018

### LINKED ISSUE #2018: Odd error message after deleting a user using the FAIRsharing UI
Good morning! I just deleted a user account at their request, and there is an odd "t is not defined" message when the deletion completes at https://fairsharing.org/profiles/editPublicProfile/8447

Screenshot from 2023-02-20 08-58-59

### PR DESCRIPTION
**Pull request by knirirr**
This will hide the spurious message mentioned in #2018.
Eventually it would be good to completely refactor this component; it's not of the best quality.

### CODE REVIEW

**Review by ramGranell — APPROVED** [review]
I removed one user and it didn't appear the undesired message.

**Comment by allysonlister** [comment]
I'm getting a 500 error when trying to load the netlify build - could I have a screenshot please of the governance? I can trust @ramGranell about the user deletion test...

**Comment by knirirr** [comment]
> I'm getting a 500 error when trying to load the netlify build - could I have a screenshot please of the governance? I can trust @ramGranell about the user deletion test...

The governance change can be seen here: https://github.com/FAIRsharing/fairsharing.github.io/pull/2023/files?file-filters%5B%5D=.json&show-viewed-files=false

Meanwhile, elasticsearch has failed on the development server, which kills the API and thus the Netlify build has nothing to which to connect. This relates to the intensive task of generating data for network graphs. I will look into it but cannot say when it will be running again.

**Review by allysonlister — APPROVED** [review]
thanks for the info - happy to approve.

**Pull request merged**
