### PR TITLE
Hossein home page #810

### LINKED ISSUE #810: Create new Home Page
designing new home page

### PR DESCRIPTION
**Pull request by hoseinmirian**

### CODE REVIEW

**Comment by hoseinmirian** [comment]
new Home page implementation.... presentation layout
- tabs section is synced with json data
- other sections will be synced with json data in an upcoming ticket ..

**Comment by terazus** [comment]
I really like the new home page, much simpler than the old one.
There's only one minor thing that i noticed:
image
I think the values should be ordered from bigger to smaller.

**Comment by hoseinmirian** [comment]
thanks. I have to ask Susanna if she agrees with that.

**Comment by hoseinmirian** [comment]
> 
> 
> thanks. I have to ask Susanna if she agrees with that.

@terazus thanks. its been approved.

**Comment by knirirr** [comment]
> > thanks. I have to ask Susanna if she agrees with that.
> 
> @terazus thanks. its been approved.

Do you mean that ordering by count has been approved? If so then it doesn't seem to be implemented.
One other thing I noticed is that clicking "view all" on one of these sections prevents the back button from returning to the home page. Is there a means of allowing this? I suspect that some users may do what I did and immediately want to return.

**Comment by hoseinmirian** [comment]
@knirirr thanks. ordering of the items count of each section (database, standard,etc) is intended.(sections position is fine where they are). in regard to clicking viewAll I will check that.

**Review by knirirr — APPROVED** [review]

**Pull request merged**
