### PR TITLE
Adding changes in static pages

### PR DESCRIPTION
**Pull request by ramGranell**
This is related to https://github.com/FAIRsharing/fairsharing.github.io/pull/1950

### CODE REVIEW

**Comment by knirirr** [comment]
I've deployed this at https://testing.fairsharing.org. It seems OK other than two blocks of repeated text in the introductory section.

**Comment by ramGranell** [comment]
Now netlify is working

**Comment by allysonlister** [comment]
Please can you add more padding to the quotes on our_curators, then it will be ready

**Comment by allysonlister** [comment]
thank you please merge!

**Review by allysonlister — APPROVED** [review]

**Pull request merged**
