### PR TITLE
Hossein add icon record #1435

### LINKED ISSUE #1435: Icons / graphical summary to highlight certain record metadata, to be shown in badges and in general information
This relates to #1119 as the icons I'm requesting should be present both in the badges and in an appropriate location in the General Information section. There are two parts to this: the icons themselves, which can be worked on separate to part 2, the integration in the site and in the record badges.

For now, please could we have some mockups of the images themselves, rather than a full implementation in FAIRsharing. Then we can refine the design before we start integrating within FAIRsharing.

Full specifications available on the internal GitBook page at https://app.gitbook.com/o/-MchtBAOWXh2gO--zz7m/s/-MkSKpWh9NA-iywIqhP_/please-can-we/record-indicators

### PR DESCRIPTION
**Pull request by hoseinmirian**

### CODE REVIEW

**Comment by hoseinmirian** [comment]
image


new infoBadge component: 
how it works:

its a component relying on a badgeBuilder class which collects all the badges based on conditions which results defining different levels consisting of different progress value, color, etc. 

** no need to change presentation component anymore! all the changes can be applied only on badgeBuilder.js and badgeBuilderData in data folder. Just define the level and the color, progress each level of each category should have and at the same time logic should be added in the badgeBuilder class for different level: all the instructions for how to add new level is commented in the badgeBuilder.js class.. its fully customizable and scalable in the future. .

- it is also very responsive. 

in regard to dynamically adding data, please make sure progressColor property is chosen based on one of our color in theme.js 
image

if u needed any custom color, just define it and then address it using the badgeData file. (check status in this file as an example.)

in case @allysonlister was wondered in the future how to commit new color and level (after logic is done tho) all the definition will be here
https://github.com/FAIRsharing/fairsharing.github.io/blob/Hossein-AddIcon-Record-%231435/src/data/infoBadgeData.json

@knirirr 
these props are by default true, in case at any. point did not want some or all of them, easily can be turned off by passing them as false in component

    showProgress: {default: true, type: Boolean},
    showProgressHover: {default: true, type: Boolean},
    showTextHover: {default: true, type: Boolean}

**Comment by allysonlister** [comment]
This is looking really great! Before I show it to Susanna, please can I have the following modifications (I'm just looking at https://deploy-preview-1581--fairsharing.netlify.app/FAIRsharing.ezznsh for reference):

1. Please don't show the numerical percentage value or the hover "progress" text for that percentage - perhaps just have a boolean so that, when we are ready to display them at some future date, we can just flip a switch and they will appear?
2. Record status is the only icon that has any values beyond either "off" (0%) or "on" (100%) at the moment. That one looks good. However, all other icons need to be displayed in their "coloured" form, as if they are already at 100%, as otherwise they are a bit drab. You can use the same colour for all "100%" versions of the icons if it's easier.

Otherwise, it's looking really great!

I presume 1) display of these icons in the search results cards, and 2) the badges that will also incorporate these icons are being dealt with elsewhere, and therefore are not within the remit of this ticket? 

Thanks!

**Comment by hoseinmirian** [comment]
1- I exactly had forseen this! so please check my last paragraph of the comment I updated. I can deactivate them easily if you want although I think they are very nice and It took a lot of work! 
2- let me try it. I update this branch: please keep checking the branch

your request needs another ticket.

**Comment by hoseinmirian** [comment]
I suggest in the future for showing percentage and color use the same practice:
25: and use (uncertain_color or at least one constant pale color like the one I sent you before in Zulip )
50 and so on...
75 and gradually it goes to be greener
100

although defining even more levels is possible.

**Comment by allysonlister** [comment]
Thank you this looks great. I will have a brief chat with Susanna about it if she has time now, and will get back to you.

**Comment by allysonlister** [comment]
Thank you, we both really like it! Susanna has the following comments:

1. Please show the record status icon first
2. Record status icon only: Irrespective of the record status value, she would like the complete ring shown. This is because record statuses aren't the same as the other icons: "deprecated" records are not "partially-completed" statuses, therefore having 25% showing in the ring doesn't make sense. Apologies for this, as I realise it means that there will be special code for the record status.
3. Susanna would like to start out with a more subdued colour for the icon rings. Therefore, for all icons except the record status, please could we change the green of the outer circle to a dark grey (the grey that matches the icon color). 
4. For record status, you have a choice based on preference: either a) keep the current color-changing ring for the record status, or b) also have that ring be the same dark grey of the others. Which looks best in your opinion?

Please let me know if you have any other questions, thanks!

**Comment by hoseinmirian** [comment]
image

and

image


Changes are pushed.!

**Comment by allysonlister** [comment]
Thanks Hossein!

All changes look great, just this one isn't quite what I asked:

> For record status, you have a choice based on preference: either a) keep the current color-changing ring for the record status, or b) also have that ring be the same dark grey of the others. Which looks best in your opinion?

It looks like you kept the green irrespective of status. I asked to either a) match the inner colour, or b) use the grey ring.
In any case, the screenshots have given me enough to go on, so please could you proceed with a grey ring for the status, but keep the icon inside coloured as they currently are?

Everything is lovely, it's looking really nice, thank you.

One final question: now that I've seen the use of the standard-database-policy logos within the icons, I find that it isn't that clear that these icons are to do with whether or not a relationship of that type is available. Is there some way to create an icon that combines standard, databsase and policy logos with the "nodes" part from the "View Relation Graph"?

e.g. a mashup of the following two for the database icon (in grey)?
logo2
nodes

**Comment by hoseinmirian** [comment]
thanks. now its ready. 

to answer your question: no its not possible at least with this branch due to the way its been designed and developed.

**Comment by allysonlister** [comment]
Thanks, looks good. 

Can you not make a new image for the database/standard/policy relationship icon logo as I described? If you really can't, then I am ready to approve. Please can you confirm? 

Also, let me know when/where I should update the hover-over text please.

Now that it's nearly there, please can you also tag @delphinedauga  as a reviewer? Thanks!

**Comment by hoseinmirian** [comment]
@allysonlister for which item the icon u are suggesting is needed from this list?
 .hasStatus()
      .hasLicence()
      .hasMaintainer()
      .hasStandard()
      .hasDatabase()
      .hasPolicy()
      .hasAPI()
      .hasPID()
      .hasCertificate()
      .getBadges()

for checking where to update it, I put the link in the first comment and mentioned ur name. tnx

**Comment by allysonlister** [comment]
I'm not really sure what your question is, so here is a very very bad mockup of what I'm trying to say (apologies to you, who has great graphics skills!)

icons

I was only wondering if we could update the icons for
.hasStandard()
.hasDatabase()
.hasPolicy()
such that they show a little inset graphic of some nodes and edges. Just a change to the little image, that's all.

Does that make more sense? Thanks!

**Comment by hoseinmirian** [comment]
ok let me see if I can add an extension on some of these image...yes it makes sense

**Review by delphinedauga — COMMENTED** [review]
Sounds good to me, nothing to add, waiting for icons with relationship (Ally remarks)

**Comment by hoseinmirian** [comment]
image

**Comment by hoseinmirian** [comment]
please let me know if netlify link is working for you. mine is broken. tnx

**Comment by allysonlister** [comment]
netlify is not working for me, but I have your screenshot, thank you!

i personally like the color you've added to the little blue "relation" part of the icons, but I know Susanna favors grey for everything other than record status for now. Please could you greyscale that, and then I think we'll be ready?

Thanks!

**Comment by hoseinmirian** [comment]
dear if i gray scale it I have to change the background of circle to white which again we ll face blended backgrounds due to the icons in the center are white

**Comment by hoseinmirian** [comment]
let me see what happens. I send screenshot here

how about this @allysonlister 
image

**Comment by allysonlister** [comment]
This looks great, thanks Hossein!

I'll approve, as everything has been addressed, thanks :)

**Review by allysonlister — APPROVED** [review]
I realize netlify isn't working right now, but from previous tests + screenshots, I'm happy to approve.

**Comment by hoseinmirian** [comment]
progress tooltip background now matches with the progress color for e.g if in the future u define ready status as 'ready_color' which is green then the progress tooltip background follow it. All u need to do is just working with the json file and things happens as expected.. Also have to turn these on as true or not passed them in the component as they are by default true.
 
image


image


last commit..

**Comment by hoseinmirian** [comment]
if no objection please approve the branch. this branch s ready for a revisit. tnx

**Comment by knirirr** [comment]
@allysonlister @delphinedauga it appears that the hover text for these icons is still a placeholder:

https://github.com/FAIRsharing/fairsharing.github.io/pull/1581/files?file-filters%5B%5D=.js&file-filters%5B%5D=.json&file-filters%5B%5D=.png&file-filters%5B%5D=.vue&show-viewed-files=true#diff-70acf9a85c2efdfa616c67041b821a00c301cde55b6aa14ab8974d26bde8b2f5

Look in src/data/infoBadgeData.json to see what I mean, e.g. 

```
 "standard": {
    "level_1": {
      "progress":"100",
      "progressColor":"dark_gray",
      "icon": "model_and_format",
      "textHover": "This is hover text for standard",
      "progressHover": "This is progress text for standard"
    }
  },
```

These can be seen at e.g. https://deploy-preview-1581--fairsharing.netlify.app/FAIRsharing.9kahy4 (should all those icons be there)?

Do you have any preferences for text here?

**Comment by allysonlister** [comment]
Thank you - I'll write up some text and put them in a comment here momentarily.

**Comment by allysonlister** [comment]
.hasStatus() - _this is already written, no need to change the hover over text for it_
.hasLicence() - At least one licence is described
.hasMaintainer() - This record has at least one maintainer
.hasStandard() - This record is related to at least one standard
.hasDatabase() - This record is related to at least one database
.hasPolicy() - This record is related to at least one policy
.hasAPI() - At least one programmatic access point is described
.hasPID() - This record is related to at least one identifier schema
.hasCertificate() - At least one certificate or community badge is described

**Comment by hoseinmirian** [comment]
All done. tnx
@delphinedauga and @allysonlister please do a final review. tnx

**Comment by allysonlister** [comment]
Looking great to me! Thank you!

**Comment by allysonlister** [comment]
I am horrible to you this morning @hoseinmirian but please could you make one small change? The icons look great on my big screen, but on smaller screens they can take over a bit:
image_2022_03_11T09_13_54_785Z

image_2022_03_11T09_15_57_743Z


Could you perhaps reduce their overall size by 10-20%, whatever seems sensible? Whatever is required that a smaller screen like the screenshots below can still have the icons in the same place without making the larger gap that appears? Thank you!

**Comment by allysonlister** [comment]
One final point. It has been pointed out to me that the icon used for the certification status (the ribbon) is also commonly used for charities and, more importantly, cancer awareness. It might not be appropriate to use it here, therefore.

For that reason, please can you find an alternative ribbon / badge that looks sufficiently different from e.g. the licence icon? Again, my apologies, but we probably shouldn't use that ribbon icon for certification - I didn't realize it at first. 
image_2022_03_11T09_19_04_898Z
A much simpler version of the image above would be good?

**Comment by delphinedauga** [comment]
I created a test record (https://deploy-preview-1581--fairsharing.netlify.app/3903) whether the badges appear correctly when the data is entered. Everything seems to be ok except for the "collection" badge. I have included my resource in the "NIH-supported data repositories" collection (https://deploy-preview-1581--fairsharing.netlify.app/3493), I have approved the two edits, to no avail, the badge does not appear.

**Comment by allysonlister** [comment]
I didn't think we had a collection badge?

**Comment by delphinedauga** [comment]
oh sorry, it's policy the one that was missing ! It's ok, it works !

**Review by delphinedauga — APPROVED** [review]
ok ! thanks

**Comment by hoseinmirian** [comment]
@allysonlister @knirirr @delphinedauga my last commit for FAIRsharing is pushed! please check and approve the branch if happy. tnx, all. 

image

**Review by delphinedauga — APPROVED** [review]
Ok !

**Review by allysonlister — APPROVED** [review]
Thank you!

**Review by knirirr — APPROVED** [review]

**Pull request merged**
