### PR TITLE
Hossein styling scroll bar #560

### LINKED ISSUE #560: Having customized scrollbar
It would be nice to have a fancy narrow scrollbar style like zulip

suggested library for this case:

- https://www.npmjs.com/package/vuebar
ex: https://github.serafin.io/vuebar/?ref=madewithvuejs.com#examples

- https://www.npmjs.com/package/vue2-perfect-scrollbar
ex:https://codesandbox.io/s/wn7q7o9ww7

### PR DESCRIPTION
**Pull request by hoseinmirian**
make the left panel scrollbar narrower and nicer. When its hovered it will show the scroll, its mainly used by google in Gmail or Zulip for e.g. it brings better UI as well as adding beauty and cosmetic to the web app. Also would like to ask @Drosophilic to review the change as its a new cosmetic feature added to the project. 

asdasdasd

Zulip e.g
please check top-left users panel in Zulip:

image

### CODE REVIEW

**Review by knirirr — APPROVED** [review]
Again, hard to review as there's a lot of commit/merge spam, but the feature does look good. It would also appear to have resolved the slightly laggy left-panel scroll I mentioned in https://github.com/FAIRsharing/fairsharing.github.io/pull/596, which is nice.

**Review by terazus — CHANGES_REQUESTED** [review]
I didn't review the code yet but I can already see issues in the deploy with the header where the content at the top of severals pages get truncated (hidden behind the header):

1. https://deploy-preview-623--fairsharing.netlify.app/#/accounts/profile => you'll need to be logged in
2. https://deploy-preview-623--fairsharing.netlify.app/#/1/ediiiiiit => should point to a 404 but doesn't anymore
3. https://deploy-preview-623--fairsharing.netlify.app/#/new
4. More generally all non search pages are affected: https://deploy-preview-623--fairsharing.netlify.app/#/community

Please, be more carefull before submitting a PR as this one still has a LOT of issues.

**Comment by hoseinmirian** [comment]
@terazus I read all. tnx. all the issues you raised are related to header prop 'app' that needs to be removed to not have absolute header. one thing its unclear a bit to me :
https://deploy-preview-623--fairsharing.netlify.app/#/accounts/profile => you'll need to be logged in
Do you mean the same hidden content problem or something had to happen when hitting this page?

**Comment by terazus** [comment]
@hoseinmirian  i mean that when you access your profile page there's a missing part at the top behind the header (especially the logout button)

**Pull request closed without merging**
