### PR TITLE
Processing notes again

### PR DESCRIPTION
**Pull request by knirirr**
Now, when processing notes are modified the relevant record will remain unapproved.

Important note: The code in this PR is separate from any question as to whether the notes are saved correctly. That is covered under https://github.com/FAIRsharing/FAIRsharing-API/issues/1034

Before commenting, please read https://github.com/FAIRsharing/FAIRsharing-API/pull/1038#issuecomment-2315617052 (then comment below).

### CODE REVIEW

**Review by ramGranell — COMMENTED** [review]
This is not working for me (I modified the processing notes for ownership request panel and they are not saved, for the RECORDS/EDITS AWAITING APPROVAL  panel they work properly). I save the processing note. By the way, we tried the same before with the same result.

**Comment by knirirr** [comment]
Before commenting, please read https://github.com/FAIRsharing/FAIRsharing-API/pull/1038#issuecomment-2315617052 (then comment below).

**Review by allysonlister — APPROVED** [review]
I am not 'close to' this bug, but everything seems to be working as expected. @delphinedauga will be able to make a more valued review though, I think.

**Comment by ramGranell** [comment]
It has the same behaviour as the current production system, i.e. it saves the processing notes in the "Ownership request" table and it adds this record "RECORDS/EDITS AWAITING APPROVAL" table. I did:
1. Go to processing note of a record (ID 1551) in "Ownership request", modify its processing notes and press "save". After that, the processing notes are saed and visible in that table.
2. I refresh the page. The processing notes of the record keep being in the "Ownership request" table but the record appears in the top of the table "RECORDS/EDITS AWAITING APPROVAL"

This is the current behaviour that happens in my production.

**Comment by knirirr** [comment]
> This is the current behaviour that happens in my production.

The same behaviour is happening for a different reason, the underlying mechanism having changed.
In the case of 1551 it is already approved but, when a processing note is added, the text of that note is sent to the server with instructions to not automatically approve the record (as happens when a super_curator saves a record) because super_curators edit records in the "awaiting approval" queue and don't want them approved until ready.
I can slightly change the server behaviour again but this may trigger unwanted changes in other places.

**Comment by knirirr** [comment]
Together with the corresponding server ticket https://github.com/FAIRsharing/FAIRsharing-API/pull/1038 this should be ready. If anyone still to review it finds anything unexpected, please give me as detailed a description as possible of the steps taken to reproduced (various components interact in ways which can be hard to spot without this).

**Review by ramGranell — APPROVED** [review]
In the Netlify running website, when checking the processing notes, it seems to work all properly:
1. processing notes are saved when written in the  OWNERSHIP REQUESTS table, 
2. when processing notes are saved and the record was not in the AWAITING APPROVAL table, the record does not appear in that table
3.  when approved an ownership request, the record does not appear in the RECORDS AWAITING APPROVAL table

**Review by delphinedauga — APPROVED** [review]

**Comment by delphinedauga** [comment]
Strange behavior I notice today (test on https://preview.fairsharing.org/curator) : 
1) when a supercurator create a processing note on a record from the ECORDS/EDITS AWAITING APPROVAL TABLE 
2) and refresh the webpage : 
-> the record disappear from the ECORDS/EDITS AWAITING APPROVAL TABLE (but stay in the HIDDEN RECORDS TABLE)

**Comment by knirirr** [comment]
@delphinedauga this is a closed PR so I have moved your comment to a ticket: https://github.com/FAIRsharing/fairsharing.github.io/issues/2389

**Pull request merged**
