### PR TITLE
Initialize back color based on registry

### LINKED ISSUE #1355: Change card shade for collections, standards and policies
We've had some feedback that it is hard to tell that one is viewing a Collection (as opposed to other record types). While we wish to maintain consistency, we would like some relatively subtle way (in addition to the Registry/Type and icon) for a user to feel like they are viewing a collection.

I'm completely open to ideas as to how to do this, but might it be possible for the "cards" (e.g. the color in the background of General Information) to be a slightly different shade for Collections? 

I don't know if it makes sense to extend this to other record types (would it make it easier for each registry to have its own shade?), but again I would be open to what would seem to you to be the optimal solution.

Please note this is quite low priority.

Thanks!

### PR DESCRIPTION
**Pull request by hoseinmirian**

### CODE REVIEW

**Comment by hoseinmirian** [comment]
preview for me is going to maintanance if its good for you then please review it. tnx

**Comment by knirirr** [comment]
> preview for me is going to maintanance if its good for you then please review it. tnx

The problem is somehow related to particular Netlify builds, not the development server. Compare, for example, https://deploy-preview-1495--fairsharing.netlify.app/

**Comment by hoseinmirian** [comment]
it seems that is working!  netlify build sometimes is weird.

**Comment by allysonlister** [comment]
Not working for me - says Maintenance Mode, sorry!

BTW Susanna and I are still in disagreement :-)

Therefore, we have decided to only pursue what we agree on for now. Please keep going with the code as requested (namely, the ability to have different card colors for each of the registries: collection, standard, database, policy) HOWEVER:

Please keep standard, database and policy cards at the "default" light tan. Only update the collection card colors as you have shown us. The color you should use is a very light blue, a bit lighter (but in the same color) as the "skype" / "github comment header" blue here:
skype

Later, as we agree, the code will be in place to adjust the other card colors. Does this make sense?

**Comment by hoseinmirian** [comment]
@allysonlister ok thanks. now then I ll ask Milo if he is happy with code then we merge  it and you can  see the actual result. in case you were not able to see the netlify  I just send here some  screenshot  of only collection due to others color will remain the same.

**Comment by hoseinmirian** [comment]
image


I used your color but it was a bit strong so I made it a bit pale same color u sent. please check if its good then approve the branch

**Comment by allysonlister** [comment]
You have been very responsive, thank you!

A small change please (thank you for your patience!) - the hyperlinks are a little harder to see with this particular shade than we thought they might be. Please can you make it just a bit lighter and a bit more grey, so that the hyperlinks show up better?

Thanks!

**Comment by hoseinmirian** [comment]
image

how about it

**Comment by hoseinmirian** [comment]
@allysonlister I need feedback today please. tnx

**Comment by allysonlister** [comment]
Susanna has requested a bit paler again. Perhaps if you could provide a few options in this shade range and we can choose? Thanks!

**Comment by hoseinmirian** [comment]
1-
image
2-
image
3-
image


and if I go paler then it will become like other records type backgrounds
3rd one is pretty close tho

and this is any other type background style to compare better:

image

**Review by knirirr — APPROVED** [review]

**Review by allysonlister — APPROVED** [review]
Susanna has chosen #2
 
thanks!

**Pull request merged**
