### PR TITLE
Improved speed of user query. #458.

### LINKED ISSUE #1543: Improved user query
As discussed in https://github.com/FAIRsharing/FAIRsharing-API/issues/458, a means to take advantage of the improved speed of a new query should be implemented in the relevant sections of the client. Presumably:

- [x] Admins' user list page.
- [x] Record editing page (for maintainer assignment).

### PR DESCRIPTION
**Pull request by knirirr**
This will greatly improve the speed at which user data loads when either viewing all users as an admin or assigning a user as a record maintainer, or your money back!

### CODE REVIEW

**Comment by allysonlister** [comment]
The preview is not loading for me, sorry!

**Review by hoseinmirian — APPROVED** [review]

**Comment by hoseinmirian** [comment]
there is some part of code not passed the code ..

**Comment by allysonlister** [comment]
Ah, I can see it now - looking...!

**Review by hoseinmirian — APPROVED** [review]

**Review by allysonlister — APPROVED** [review]
That is sooo much quicker - thank you very much!

**Comment by knirirr** [comment]
> there is some part of code not passed the code ..

Yes, I am aware of that. Unfortunately, wrestling with the horrid tooling one seems to have to use for Javascript is taking a while.

**Pull request merged**
