### PR TITLE
Gained skills for Champions #1903

### PR DESCRIPTION
**Pull request by ramGranell**
This is the first attempt for ticket #1903 . If you go https://deploy-preview-2142--fairsharing.netlify.app/community_champions/our_champions
There are two champions with gained skills: Kyle Copas (one skill) and Annie Kristensen IMPORTANT, this is fictional data and I need to remove fictional data from the file src/data/communityCurationCohorts.json until the real data is available.

I also included ticket #2143 request here. There are two cases when the champions is tagged as curation expert:
1. It has the Curation Expert but not Early Adapter (see champion Gabiel Pelletier)
2. It has the Curation Expert  AND Early Adapter  (see champion Joe Miller)

### CODE REVIEW

**Review by allysonlister — APPROVED** [review]
This looks as I would expect. When putting into production, please could you link this value to Lindsey's tile. Thank you!

**Comment by knirirr** [comment]
@allysonlister am I correct in thinking that you want this to be deployed without any gained skills data being available, and for these to be added later?

If so then this deployment can be done once @ramGranell has had a moment to remove the fake demo data.

**Review by knirirr — APPROVED** [review]
This code seems to do the trick, but shouldn't be merged until the fake data have been removed, of course.

**Comment by allysonlister** [comment]
This should be deployed with NOTHING added to anyone yet, other than the Curation expert for Lindsey. Thanks!

**Comment by ramGranell** [comment]
> This should be deployed with NOTHING added to anyone yet, other than the Curation expert for Lindsey. Thanks!

All data about Champions as it was but only adding Curation Expert foir Lindsey.

**Pull request merged**
