### PR TITLE
Apply ally's comments

### LINKED ISSUE #1124: Additional Community Page Updates
Please see some additional updates for the community page:

- [x] Table order should go back to what it was: Adopters, Activities, Governance (sorry!)
- [x] The three "title blocks" for Adopters, Activities, Governance should go at the very top of the page underneath the title/subtitle heading
- [x] The title/subtitle heading should be put back - I'm not sure why it was deleted? (See https://github.com/FAIRsharing/fairsharing.github.io/issues/1085#issuecomment-866634316)
- [x] Remove the "how to cite us" sentence.
- [x] Using the same style of grid (3-column, 5-column or what works best) as used for the official reports, we simplify the adopters table to just show logos only (no hyperlinks)
 - eLife
 - Elsevier
 - EMBO Press
 - F1000
 - GigaScience
 - PLoS
 - Taylor and Francis
 - Wellcome
 - Wiley
 - Springer Nature
 - PeerJ - not in the existing community page
 - Hindawi - not in the existing community page
 - Cambridge University Press - not in the existing community page
 - Oxford University Press - not in the existing community page
 - The Royal Society Publishing - not in the existing community page
- [x] In the "Adopters" section, there is this text which is no longer quite correct with respect to recommendations: "Create Recommendations by registering their data policy, and then link it to standards and/or databases recommended in the policy; and/or ". I suggest we change the text to "Recommend resources by registering their data policy..." etc  The link should be https://deploy-preview-1102--fairsharing.netlify.app/#/search?isRecommended=true&page=1
- [x] Remove the sentence "Learn more about the FAIRsharing community, and please do not hesitate to contact us if you are interested in working with us."
- [x] Replace "We cannot list all of our adopters, but we've listed here those publishers that use FAIRsharing to define and refine their data policy." with "We cannot list all of our adopters, but we've listed here some publishers that use FAIRsharing to define and refine their data policy."
- [x] Replace "Global Organizations" title with "Other Organisations". Then replace the table with a 4-column, 1-row table with the following hyperlinked logos 
  - RDA
  - GO FAIR
  - FORCE11
  - ELIXIR https://elixir-europe.org/
- [x] Modify the "Meet the Team" section. 4 people per row perhaps? Order:
First row
 a. Allyson - Content and Community Lead
 b. Milo - Technical Lead
 c. Susanna - Principal Investigator and Founder
 d. Philippe - Co-Founder
- [x] Second row (Titles tbc)
 e. Ramon
 f. Hossein
 g. Dom 
 h. Delphine 
- [x] Remove the link on the team member's names, and have the little house logo for everyone link to the same URL: https://datareadiness.eng.ox.ac.uk/#people 
- [x] Change URL in "Data Readiness Group" within the sentence "The operational team is based in the Data Readiness Group..."  to link to https://datareadiness.eng.ox.ac.uk
- [x] Remove this sentence: "FAIRsharing also operates as a joint Force11/RDA working group, reaching out to the broader community. "
- [x] Make the pictures of us slightly smaller 
- [x] All logos on the page, and also our photos, should be in black and white.
- [x] The stakeholder Advisors list should be replaced with the one at the google doc I sent to @knirirr offline.

### PR DESCRIPTION
**Pull request by hoseinmirian**
remained feedback from Ally applied...

please check community page

### CODE REVIEW

**Comment by allysonlister** [comment]
Thank you for the updated page. I have looked at the deploy preview and have the following comments. 

From https://github.com/FAIRsharing/fairsharing.github.io/issues/1124:

1. Title blocks for tables
```
Table order should go back to what it was: Adopters, Activities, Governance (sorry!)
The three "title blocks" for Adopters, Activities, Governance should go at the very top of the page underneath the title/subtitle heading
```
Perhaps I wasn't clear enough here, but the table order and the title blocks should be in the same order. This means the title blocks should be in the order Adopters, Activities, Governance to match the table order, thanks.

2. Advisors
```
The stakeholder Advisors list should be replaced with the one at the google doc I sent to @knirirr offline.
```
This isn't quite the same as in the gdoc I sent you. I immediately notice that the item for Michael Ball should **not** have "UK" in it. Please can you remove "UK" and carefully check that all other advisor entries match what is in the gdc.

3. Logos
which
Which image is this? Please can you see if whichever logo this is has a version of the image with some text to make it clear who it is, or perhaps add some small text to the bottom of the image so that our users know which org this is.

4. Now that we have two tables with small borders around the cells, please can the same borders be used for the table under "Other Organisations" to keep it consistent?
5. This is a new request, sorry, but please can we move "Adopter" (the title and its internal bookmark) to just before the table and text that begins with "A selection of official reports from funders....." otherwise we risk people missing that important table with funders recommending ("adopting") FAIRsharing.

**Comment by allysonlister** [comment]
I also just noticed that the following update from #1124 hasn't been done yet

```
Ramon - Data Enrichment and Quality Manager
Hossein - Web Developer
Dom - Front End Manager
Delphine - Curation Manager
```
This update was provided in the comments of #1124 and has yet to be implemented. Please note the change for Dom's title.

**Comment by hoseinmirian** [comment]
@allysonlister please check the latest changes and approve if satisfied . tnx

**Comment by allysonlister** [comment]
Thank you for these updates.

- [x] Please can you add a link to Delphine's ORCID: https://orcid.org/0000-0003-3152-1194 (Apologies I missed this before).
- [x] This item hasn't been done yet: [...] but please can we move "Adopter" (the title and its internal bookmark) to just before the table and text that begins with "A selection of official reports from funders....." otherwise we risk people missing that important table with funders recommending ("adopting") FAIRsharing.
- [x] Logo: It seems I was a little unclear for this item. Here's what I said: 
> Which image is this? Please can you see if whichever logo this is has a version of the image with some text to make it clear who it is, or perhaps add some small text to the bottom of the image so that our users know which org this is.
What we would like is **not** to add text to every organisation, as you have done. Rather, we would only like you to find a version of the logo that includes text, e.g. a black and white version of what's at the bottom of this page: https://royalsociety.org/about-us/ as this logo has text just below it.

Please let me know if this makes sense.

thanks!

**Comment by hoseinmirian** [comment]
@allysonlister your changes request is done. Please check netlify link. tnx!

**Comment by allysonlister** [comment]
Thanks for this!

- [x] Susanna has asked over skype yesterday for you to please add our new Stakeholder advisor, Sowmya Swaminathan, Springer Nature. It also looks like our recent changes to that list have meant that they are no longer in alphabetical order, so please can you adjust the stakeholder list so it is in alphabetical order by surname. Again, apologies for the additional request at the end of the ticket.
- [x] The "Wiley" logo still appears a bit jagged - is it possible for you to find a higher-res version of that?
- [x] The combination springer nature / BioMed Central logo is looking a bit small compared to the others. Can you remake it a bit larger, in good resolution?

This page is looking really good, and all other changes have been applied. Thank you for the work!

**Review by allysonlister — CHANGES_REQUESTED** [review]
Please see my comment in the main thread. Apologies still learning the ropes of reviewing PRs.

**Comment by hoseinmirian** [comment]
@allysonlister 
please check and if your happy then I ll do the merge

**Comment by allysonlister** [comment]
Ok - not sure how to update my review, so just adding this as a comment here.

Thanks for your updates.

- [x] The changes I asked to be made to the **stakeholder** advisors have accidentally been made to the **executive** advisors. Please can you move Sowmya to the _stakeholder_ group, and alphabetise the stakeholder group.

All other changes have been implemented - thank you very much!

**Comment by hoseinmirian** [comment]
> 
> 
> Ok - not sure how to update my review, so just adding this as a comment here.
> 
> Thanks for your updates.
> 
>     * [x]  The changes I asked to be made to the **stakeholder** advisors have accidentally been made to the **executive** advisors. Please can you move Sowmya to the _stakeholder_ group, and alphabetise the stakeholder group.
> 
> 
> All other changes have been implemented - thank you very much!

applied changes. Surnames are alphabetically sorted. @allysonlister please review. tnx

**Comment by allysonlister** [comment]
I don't see a link to go through to this particular deployment? Sorry if I'm just being blind! Thanks!

**Comment by hoseinmirian** [comment]
> 
> 
> I don't see a link to go through to this particular deployment? Sorry if I'm just being blind! Thanks!

there is a review button on top right If I am right then you can press and approve the branch..
There it is!:
https://deploy-preview-1174--fairsharing.netlify.app/

**Comment by allysonlister** [comment]
Thanks for the update. All changes mentioned previously are working. 

There is one last thing to do with tables - thank you very much for your patience.
image_2021_07_30T14_44_00_115Z

As there are only 4 logos here, having the 3-column layout looks odd. Please could this "Other Organisations" table **only** be made into a 4-column layout when the width of the window is big enough?

Thanks!

**Comment by hoseinmirian** [comment]
@allysonlister 
Thanks for comments. I applied the last comment you had in the code. Its now 4 items in a row and when its small screen as usual each time  becomes full width

**Review by allysonlister — APPROVED** [review]
Thank you - all changes look great!

**Comment by hoseinmirian** [comment]
@knirirr if you are also happy with the changes please approve and then I will do a merge. thanks

**Pull request merged**
