### PR TITLE
Rg update governance text#2149

### PR DESCRIPTION
**Pull request by ramGranell**
This is related to ticket #2149 and I think the three requirements of the ticket are done here:
The page is this one https://deploy-preview-2156--fairsharing.netlify.app/communities

### CODE REVIEW

**Comment by allysonlister** [comment]
This may be a day or two until I can get the chance to confirm with SAS. Thanks!

**Comment by ramGranell** [comment]
> This may be a day or two until I can get the chance to confirm with SAS. Thanks!

Sure, not a problem, you can pass her the Netlify link to show how it would be

**Comment by allysonlister** [comment]
Please can you screenshot it or just ping me when the deploy is up again? I'm not sure if Susanna will have time to look now that her schedule has changed, so I may just approve this anyway though I'll ask her first.

**Review by allysonlister — APPROVED** [review]
When Netlify was working this all looked good, so happy to approve.

**Pull request merged**
