### PR TITLE
Fixed bug where additional fields aren't shown due to outdated check on changed schema fields

### PR DESCRIPTION
**Pull request by knirirr**
This must be merged when https://github.com/FAIRsharing/FAIRsharing-API/pull/725 is merged, but not before.

### CODE REVIEW

**Comment by allysonlister** [comment]
None of the new pulldowns of those fields that were radio toggles are visible, see in https://deploy-preview-2072--fairsharing.netlify.app/1998/edit in the Additional information tab (identical to what is reported in zulip):

1. Citation to related publications
2. Data access for pre-publication review
3. Data Contact Information
4. Data versioning

Their values are retained (see https://deploy-preview-2072--fairsharing.netlify.app/1998), so the info is there - it appears to just be a UI issue.

Also, when I try to create a record, I get the following:
image

AxiosError: Request failed with status code 422 { "metadata": [ "The property '#/data_curation/type' value \"not found\" did not match one of the following values: manual, automated, manual/automated, none in schema https://api.fairsharing.org/model/database_repository_schema.json", "The property '#/data_versioning' value \"not found\" did not match one of the following values: yes, no in schema https://api.fairsharing.org/model/database_repository_schema.json", "The property '#/data_access_condition/type' value \"not found\" did not match one of the following values: open, partially open, controlled in schema https://api.fairsharing.org/model/database_repository_schema.json", "The property '#/data_contact_information' value \"not found\" did not match one of the following values: yes, no in schema https://api.fairsharing.org/model/database_repository_schema.json", "The property '#/data_deposition_condition/type' value \"not found\" did not match one of the following values: open, controlled in schema https://api.fairsharing.org/model/database_repository_schema.json", "The property '#/citation_to_related_publications' value \"not found\" did not match one of the following values: yes, no in schema https://api.fairsharing.org/model/database_repository_schema.json", "The property '#/data_access_for_pre_publication_review' value \"not found\" did not match one of the following values: yes, no in schema https://api.fairsharing.org/model/database_repository_schema.json" ] }

**Comment by knirirr** [comment]
Here's what I see when I try editing that record:

Screenshot from 2023-05-25 14-37-58

I was able to create a record successfully.

https://deploy-preview-2072--fairsharing.netlify.app/4709/edit

It is not clear why the behaviour for you has been different.

**Comment by allysonlister** [comment]
Interesting!

I've switched browsers and will now summarise again. How many browsers did you test on btw? Would be interesting to see what you found if you were on the same ones I was.

1. The behaviour from my previous comment was all on Firefox (113.0.2 (64-bit), Ubuntu). As it worked for you, and it worked in number 2 (Chrome), I tried force-refreshing the browser and all seems well now. If you confirm Firefox is ok for you too, I'm happy.
2. I tried again using Chrome (Version 113.0.5672.126 (Official Build) (64-bit), Ubuntu), and was able to get the behaviour your experienced.

I am just conferring with Delphine and Ramon about displaying values when 'no' or 'not found'; you've implemented exactly as we asked, but looking at it now, it seems odd to only show the value if "yes", and not if 'no' or 'not found. Will get back to you shortly on this.

**Comment by knirirr** [comment]
I'm using Firefox, but this will probably be related to something else (cached data, server didn't restart immediately, or something like that). 
When you mention not showing values other than 'yes', are you referring to the record's main page?
If so, this is not code I've touched recently and it will require investigation.

**Comment by allysonlister** [comment]
I have just conferred with Delphine and Ramon about displaying values when 'no' or 'not found'; you've implemented exactly as we asked, but looking at it now, it seems odd to only show the value if "yes", and not if 'no' or 'not found. They agree that, as there are now three options, this field should be visible at all times, and not just if it has a 'yes' value. For example, I changed data contact information to 'no' and citation to related publications to 'not found' in https://deploy-preview-2072--fairsharing.netlify.app/1998 but neither are visible. Can you make all of these new yes/no/not found fields visible at all times please?

I understand if this should have a separate ticket; and yes, I'm referring to the main page of the record. thanks!

**Comment by ramGranell** [comment]
All works properly for me. The first time I tried I had the same problem that @allysonlister described (maybe before the DB was not ready). @allysonlister you can try it again to check if you are having problems when creating a DB.

Question about the display of the fields in the record view (not edit view), this is what I see depending on the field value:
-Data access condition: it is displayed always independently of the field value
-Data curation: it is displayed always independently of the field value
-Data deposition condition: it is displayed always independently of the field value

-Citation to related publications: it is displayed only if yes value
-Data access for pre publication review: it is displayed only if yes value
-Data contact information: it is displayed only if yes value
-Data versioning: it is displayed only if yes value

Is this the behaviour that the want? 
In the edit view all the features appear with their assigned values and the scroll-down menus have all possible values.

**Comment by allysonlister** [comment]
Thank you all!

> -Citation to related publications: it is displayed only if yes value
> -Data access for pre publication review: it is displayed only if yes value
> -Data contact information: it is displayed only if yes value
> -Data versioning: it is displayed only if yes value

Sorry if I wasn't clear in my last comment - the quoted items above should all be visible at all times, as the other fields are now. I believe this will be implemented within this ticket, but @knirirr mentioned it might go in another ticket... Not sure if I should approve if it might still be added in this ticket?

**Comment by knirirr** [comment]
I'll do a separate ticket for that.

**Review by ramGranell — APPROVED** [review]

**Pull request merged**
