### PR TITLE
Add logo in record display

### LINKED ISSUE #1332: Enabling logos for records
This is related to a Zulip discussion at https://pyroeis.oerc.ox.ac.uk/#narrow/stream/8-FAIRsharing-Rebuild/topic/UI.20Feedback/near/33557

Please can we begin work on enabling logos for all record types. From what was said in the Zuplip discussion, I believe the following things need to occur:

1. Creation of UI code to add/remove/update logos on a record.
2. Copying logos that are already present from the legacy (collections only) to their equivalent records on new site.
Thanks!

### PR DESCRIPTION
**Pull request by hoseinmirian**
upload a logo and then save and exit and see the result.

### CODE REVIEW

**Review by knirirr — APPROVED** [review]
Works for me:
Screenshot 2022-01-24 at 15 16 27

**Comment by allysonlister** [comment]
Sorry, I can't see the netlify build link?

**Comment by knirirr** [comment]
> Sorry, I can't see the netlify build link.

There isn't one. I don't know why and haven't had time to investigate.

**Comment by allysonlister** [comment]
Thanks - Hossein has pointed me at https://github.com/FAIRsharing/fairsharing.github.io/pull/1436#issuecomment-1020430550 and I'm looking there.

**Pull request merged**
