### PR TITLE
updated info on community curation page

### PR DESCRIPTION
**Pull request by allysonlister**

### CODE REVIEW

**Comment by allysonlister** [comment]
Linking https://github.com/FAIRsharing/fairsharing.github.io/issues/1949 to this...

Also, Susanna wishes some further edits, please wait until I comment again before reviewing - thanks!

**Comment by allysonlister** [comment]
Just made a few updates - I'll let you know when I'm ready for review (not yet ;-) ) thanks!

**Comment by allysonlister** [comment]
Please can someone look at this now? when I look at https://deploy-preview-1950--fairsharing.netlify.app/community_curation, I can't see why the third paragraph of the top section isn't being displayed.

Also, I'd like the list of three items in the first paragraph to be an itemised list and not one long sentence, but I don't know how to do that.

Finally, I'd like to make a small update to our_curators, but not sure if I should do that in this branch or another? 

Thanks!

**Comment by ramGranell** [comment]
> Please can someone look at this now? when I look at https://deploy-preview-1950--fairsharing.netlify.app/community_curation, I can't see why the third paragraph of the top section isn't being displayed.

It is not displayed as it is not indicated to be displayed (check here to see how it was displayed the previous paragraphs:
https://github.com/FAIRsharing/fairsharing.github.io/blob/community_curation_1949/src/views/Static/CommunityCuration/CommunityCuration.vue#L12)

> 
> Also, I'd like the list of three items in the first paragraph to be an itemised list and not one long sentence, but I don't know how to do that.

This is more complex as you need to use Vue elements such as: https://github.com/FAIRsharing/fairsharing.github.io/blob/community_curation_1949/src/views/Static/CommunityCuration/CommunityCuration.vue#L122 


> 
> Finally, I'd like to make a small update to our_curators, but not sure if I should do that in this branch or another?
> 

As it is also related to curators and it is small, you can try to do it here as well.

My advise is that I can create a PR over your branch to modify this. You can check it and if you are happy you merged, it to this branch.

> Thanks!

**Comment by allysonlister** [comment]
Thanks @ramGranell - please would you make those changes to this file for me? Then I will make the updates to the our_curators file at the same time.

Thanks!

**Comment by allysonlister** [comment]
Actually, I'm not sure how to add this to the top of our_curators, as I don't know what elements to do for the quotes. So, I'll put it here and ask you very nicely to add this please?

At the top of our_curators, before all of the curators' tiles, please can you put the following two quotes? Happy to have them tile next to each other when the window is wide enough, then go one after the other when the window narrows.

_The Community Curator Programme at FAIRsharing.org is a great working example demonstrating when data communities work FAIR together, they can sustain FAIR innovation together._
**Lindsey Anderson** - Life Science, Omics

_I find myself dedicating more and more time on curating […] In doing so, I experienced how much standards are key, but also that [these] curation skills and activities are indeed valuable activities that make a difference in increasing discoverability and reusability of resources we want to share._
**Geneviève Michaud** - Humanities and Social Science

**Comment by ramGranell** [comment]
Sure, next Monday I will do the PR as I have been with problems with another branch

**Comment by allysonlister** [comment]
Please note that both of these tasks need to happen before Thursday please, thanks!

**Pull request merged**
