### PR TITLE
Dom rewrite record tests

### PR DESCRIPTION
**Pull request by terazus**

### CODE REVIEW

**Comment by knirirr** [comment]
These now run on my Mac. However, there's one console warning from running them:

```
    console.error node_modules/vue/dist/vue.runtime.common.dev.js:621
      [Vue warn]: Invalid prop: type check failed for prop "items". Expected Array, got Object 
      
      found in
      
      ---> <VSelect>
             <VForm>
               <VCard>
                 <EditProfile>
                   <Root>
```

This happens after running tests/unit/views/Users/EditProfile.spec.js.

**Comment by terazus** [comment]
@knirirr Are you sure it's not related to the latest changes you made to editprofile.vue with the new profile type field?

**Comment by knirirr** [comment]
I don't know; it's not something I've seen before. Are you able to reproduce it on your system?
Anyway, everything else runs as expected, so you might as well merge this.

**Comment by terazus** [comment]
Nope not able to reproduce, neither locally, neither on github.

**Comment by knirirr** [comment]
Yet another mystery, then. I'll have to try it on another system some time, probably next week.

**Review by knirirr — APPROVED** [review]

**Pull request merged**
