### PR TITLE
New tool (Argos) in the community) #2168

### PR DESCRIPTION
**Pull request by ramGranell**
New tool called "OpenDMP Software and ARGOS service" It is the last tool added in "Tools" section: https://deploy-preview-2170--fairsharing.netlify.app/communities 
I abbreviated the text and a little the name, please check it if tis correct (see the original text in the google form).

### CODE REVIEW

**Comment by allysonlister** [comment]
Let's make one final update to the text as follows, to make it all a bit shorter:

Title: ARGOS and OpenDMP
Text: Available as a standalone service (OpenDMP) and via the OpenAIRE catalogue and EOSC Portal (ARGOS), this service simplifies the management, validation, monitoring and maintenance of Data Management Plans (DMPs). The FAIRsharing component within ARGOS/OpenDMP templates allows researchers to select information from a trusted resource when creating DMPs.

Thanks!

**Comment by ramGranell** [comment]
> Let's make one final update to the text as follows, to make it all a bit shorter:
> 
> Title: ARGOS and OpenDMP Text: Available as a standalone service (OpenDMP) and via the OpenAIRE catalogue and EOSC Portal (ARGOS), this service simplifies the management, validation, monitoring and maintenance of Data Management Plans (DMPs). The FAIRsharing component within ARGOS/OpenDMP templates allows researchers to select information from a trusted resource when creating DMPs.
> 
> Thanks!

Done, now it seems better.

**Review by allysonlister — APPROVED** [review]
All looks good. If there is any way to pad out the sides of the argos logo such that it is more visible (even if smaller) within the image space, then please do so. If this is too tricky, please ignore and consider this approved.

**Comment by ramGranell** [comment]
I changed the size and now it is clearly see it at the top of the card.

**Pull request merged**
