### PR TITLE
Linkable ROR icon for organisations in the record page

### PR DESCRIPTION
**Pull request by ramGranell**
This is related to ticket #2109. A good example it is this record https://deploy-preview-2130--fairsharing.netlify.app/FAIRsharing.wkggtx Check the organisations in that section.

@knirirr , you can note, that Codacy complains saying that "Current Status: Not Analyzed " meaning that it is not able to analyse the code.

### CODE REVIEW

**Comment by allysonlister** [comment]
Thank you - the links look good, and I like the size and placement of the ROR logos.

When you click on the ROR logo it loads by default in the current page, while when you click on the FS organisation link it loads by default in a new tab. I am agnostic about the default behaviour, but I would like both of these clicks to behave the same. If you would like an opinion (though I am happy to hear other ideas), I'd suggest opening both FS orgs and ROR links in a new tab.

Thanks!

**Comment by ramGranell** [comment]
> Thank you - the links look good, and I like the size and placement of the ROR logos.
> 
> When you click on the ROR logo it loads by default in the current page, while when you click on the FS organisation link it loads by default in a new tab. I am agnostic about the default behaviour, but I would like both of these clicks to behave the same. If you would like an opinion (though I am happy to hear other ideas), I'd suggest opening both FS orgs and ROR links in a new tab.
> 
> Thanks!

This is changed and a new tab is open when pressing the ROR icon.

**Review by allysonlister — APPROVED** [review]
All looks great, thanks!

**Review by knirirr — APPROVED** [review]
In this case I think that the codacy warning can be ignored (I had a long discussion with their support about this sort of thing some time ago).

**Pull request merged**
