### PR TITLE
Hossein update add content page #1468

### LINKED ISSUE #1468: Enhancement: Add Content page
As the number of users attempting to upload data to our registry continues to climb, @delphinedauga and I decided that we are not being clear enough with our criteria for inclusion. To help our users, @delphinedauga has created an absolutely fantastic mockup of an update to https://beta.fairsharing.org/new that what we think might help provide some clarity (and @SusannaSansone has approved this change). 

All relevant parties should have access to the mockup here: https://docs.google.com/presentation/d/11YxniOAek5qppO2FxwOGf3Ougp3LZtDIiVDQzK6SkAQ/edit?usp=sharing

Please could you make these changes to https://beta.fairsharing.org/new, modifying the mockup as required to align with FAIRsharing formatting / colors? To be clear, we do not need the page to look **exactly** like this. You are best placed to ensure that the new page has the correct FAIRsharing look and feel. Please let us know if you have any questions.

Thanks!

### PR DESCRIPTION
**Pull request by hoseinmirian**
new layout just been implemented.

### CODE REVIEW

**Review by knirirr — APPROVED** [review]

**Comment by knirirr** [comment]
I only noticed after approving this that three of the icons (not databases) look the same - presumably that's not intended.

**Comment by hoseinmirian** [comment]
> I only noticed after approving this that three of the icons (not databases) look the same - presumably that's not intended.

its now fixed in the last commit

**Comment by allysonlister** [comment]
The same is true for this deploy - it's just loading a blank page. @delphinedauga can you see anything here, and provide your comments please?

**Comment by delphinedauga** [comment]
Also have a blank page :/

**Comment by hoseinmirian** [comment]
@knirirr may I ask how curators can check the deploy?

**Comment by knirirr** [comment]
> @knirirr may I ask how curators can check the deploy?

The options are:

1. We solve the mystery of your builds failing to render.
2. Curators pull your branches and run them locally.
3. You show them your work in a meeting.

...this can be discussed on Monday morning.

**Comment by hoseinmirian** [comment]
@allysonlister 

changes applied
image

**Review by allysonlister — APPROVED** [review]
thank you!

**Pull request merged**
