### PR TITLE
Harmonizing all icons with font awesome #326

### PR DESCRIPTION
**Pull request by hoseinmirian**
@Drosophilic please note icons are selected according to my taste so if you and your team need to change them you can refer to https://fontawesome.com/icons?d=gallery

### CODE REVIEW

**Review by terazus — CHANGES_REQUESTED** [review]
- [x] Missing icon in FilterChips.vue => use `close-icon="fa-times-circle"`
- [x] Remove mdi example from vuetify plugin file icons.js.
- [x] Change iconlibrary in vuetify.js plugin file to "fa"

**Comment by knirirr** [comment]
@hoseinmirian the changes requested at https://github.com/FAIRsharing/fairsharing.github.io/pull/544#pullrequestreview-505645478 seem not to have been done, yet another review has been requested.
These changes will have to be done before another review.

**Comment by hoseinmirian** [comment]
> changes will have to be done before another review

I already ticked them. I am wondering why its unticked again. they were done before requesting changes. codes were already done before your review

**Comment by knirirr** [comment]
> I already ticked them. I am wondering why its unticked again. they were done before requesting changes. codes were already done before your review

I unticked them as it would appear that the work hasn't been done yet. 
For example, here's a screenshot of the Netlify build for this PR with missing "close" icons on the filter chips, meaning that they cannot be dismissed. 

Screenshot 2020-10-12 at 14 30 26

Here are the other two:

https://github.com/FAIRsharing/fairsharing.github.io/blob/harmonizing-all-icons-with-FontAwesome-%23326/src/plugins/vuetify.js

https://github.com/FAIRsharing/fairsharing.github.io/blob/harmonizing-all-icons-with-FontAwesome-%23326/src/plugins/icons.js

**Comment by hoseinmirian** [comment]
> 
> 
> > I already ticked them. I am wondering why its unticked again. they were done before requesting changes. codes were already done before your review
> 
> I unticked them as it would appear that the work hasn't been done yet.
> For example, here's a screenshot of the Netlify build for this PR with missing "close" icons on the filter chips, meaning that they cannot be dismissed.
> 
> Screenshot 2020-10-12 at 14 30 26
> 
> Here are the other two:
> 
> https://github.com/FAIRsharing/fairsharing.github.io/blob/harmonizing-all-icons-with-FontAwesome-%23326/src/plugins/vuetify.js
> 
> https://github.com/FAIRsharing/fairsharing.github.io/blob/harmonizing-all-icons-with-FontAwesome-%23326/src/plugins/icons.js

its a weird situation I never seen. I have changed and pushed all those changes and now as you can see I have nothing to commit cz my git says nothing to commit.. my updated branch is not sync with server one.. maybe there has been some issue while pushing data to github. 
image

**Comment by hoseinmirian** [comment]
@knirirr I double checked and I am sure I did push those as the link below shows the corresponding commit. Please visit to see the changes. I am just suprised why github code is not updated with what I last time pushed. 
https://github.com/FAIRsharing/fairsharing.github.io/pull/544/commits/c832d36d4b3e78173c63a9eb96cb654b3c83440e

**Comment by knirirr** [comment]
Your screenshot above suggests that a push was forgotten.
Anyway, we'll take a look at this soon.

**Comment by hoseinmirian** [comment]
> 
> 
> Your screenshot above suggests that a push was forgotten.
> Anyway, we'll take a look at this soon.

I do not think so. If I had forgotten this commit would not exist in GitHub. 
https://github.com/FAIRsharing/fairsharing.github.io/pull/544/commits/c832d36d4b3e78173c63a9eb96cb654b3c83440e

**Review by knirirr — APPROVED** [review]

**Review by terazus — APPROVED** [review]

**Pull request merged**
