### PR TITLE
Card column fix for #571.

### PR DESCRIPTION
**Pull request by knirirr**
This was overlooked earlier (apologies). Fixes a bug with the card stack display described in #571 .

### CODE REVIEW

**Comment by terazus** [comment]
This PR is made to the wrong branch :)
Otherwise its fine so just redo a PR to dev and merge it.

**Review by terazus — CHANGES_REQUESTED** [review]
wrong branch

**Comment by knirirr** [comment]
Branch corrected!

**Comment by terazus** [comment]
> 
> 
> Branch corrected!

You can merge then :)

**Pull request merged**
