### PR TITLE
Adding new social networks accounts

### PR DESCRIPTION
**Pull request by ramGranell**
This is related to: #2178 I added also the X accounts that there were not in the file. The web is here https://deploy-preview-2179--fairsharing.netlify.app/community_champions/our_champions

### CODE REVIEW

**Comment by allysonlister** [comment]
@debsethorpe@hcommons.social for Debs Thorpe, as listed in the spreadsheet.

@neuropelletier@mastodon.online for Gabriel Pelletier


hang on, am I only checking X accounts? I don't see any mastodon things appearing

**Comment by ramGranell** [comment]
> @[debsethorpe@hcommons.social](mailto:debsethorpe@hcommons.social) for Debs Thorpe, as listed in the spreadsheet.
> 
> @[neuropelletier@mastodon.online](mailto:neuropelletier@mastodon.online) for Gabriel Pelletier
> 
> hang on, am I only checking X accounts? I don't see any mastodon things appearing

Well, I thought that this is for creating the social networks content in the json file that contains the information for the Champions that I need to use in the email. I also updated the X accounts, and you can see the file https://github.com/FAIRsharing/fairsharing.github.io/pull/2179/files#diff-826c2eedad125739a773a0845bb36cdbbe7b5013e5196e11fec560bf48c0ba6d

**Comment by allysonlister** [comment]
Ah I see - I was checking the our_champions page to see if those updates were visible there. Perhaps that should just be a separate ticket, as the mastodon socials aren't visible there but you may not be doing that work as part of this ticket?

The values in the json file look good. I just realised I forgot one: Joy Davidson has an X account: @jd162a

thanks

**Comment by allysonlister** [comment]
Should I approve now that Joy's twitter handle has been added? Or should I wait for the mastodon additions to the our_champions page? thanks!

**Comment by ramGranell** [comment]
Ok, I added the new account that you told me in the json file. About adding the Mastodon information visible in the frontend should be other ticket.

**Comment by allysonlister** [comment]
OK I'll approve then - please could you add a ticket for the front end? Thanks!

**Review by allysonlister — APPROVED** [review]
Thanks, all look good!

**Pull request merged**
