### PR TITLE
Rg 2024 new champions

### PR DESCRIPTION
**Pull request by ramGranell**
This is for new champions #2193 
The new curators for 2024 can be see here:
https://deploy-preview-2199--fairsharing.netlify.app/community_champions/our_champions

### CODE REVIEW

**Comment by ramGranell** [comment]
Adding the Champions that keep in 2024 from the spreadsheet.

**Comment by allysonlister** [comment]
Thanks!

As discussed in our meeting, I have updated Debora Drucker and Stephen Serjeant - as listed in our "Intakes" spreadsheet, please can these two be listed as active for 2024? Once that's done, everything else looks good and I'm happy for you to publish these updates. Thanks!

**Comment by allysonlister** [comment]
However, it seems some linkedin references as listed within our "Intakes" spreadsheet aren't included on the champion page?

e.g.

Christian: www.linkedin.com/in/christian-bonatto-minella-780b7710
Priya: https://twitter.com/priya__arasu and https://www.linkedin.com/in/priyadarshini-thirunavukkarasu-53107a25/

Thanks!

**Comment by allysonlister** [comment]
I now see Stephen as active, but Debora D is still listed as an alumnus?

**Comment by allysonlister** [comment]
This is entirely my fault for not remembering to tell you sooner, but please can you update Kay Burrow's email address to k.e.burrows@outlook.com? She has update her ORCID profile such that this email address is primary and visible to trusted parties.

I've removed her organisational affiliation for now from her user profile. Please can you make sure that it is removed from her Champions tile as well (user 8056)?

**Comment by allysonlister** [comment]
Everything else looks great, thanks.

**Review by allysonlister — APPROVED** [review]
looks great, thank you!

**Pull request merged**
