### PR TITLE
Search download 1734

### LINKED ISSUE #1734: Summary spreadsheet download button
A number of users have made requests to us recently where they would like to have a look at search results from FAIRsharing via a spreadsheet. While this can be done internally on a case-by-case basis, it is time consuming for our team. While we would like our users to retrieve most of the record metadata by calling the API or browsing the record, a simple spreadsheet for this purpose would help users. However, we would like to only allow logged-in users to do this, to discourage spamming of such a button.

 I suggest the button should go in two places:

1. In collections (allowing them to download a summary of collection members)
2. In search result pages

How about for search results we put it as another icon as part of the pair in the top right that allows you to change between cards and list of search results? Could go in the same place for collections.
example

The fields of the spreadsheet should be minimal, e.g.

FAIRsharing URL | FAIRsharing DOI (where present) | Record Name | Record homepage URL

### PR DESCRIPTION
**Pull request by knirirr**
This addresses #1734.
There's another PR to deal with it on the server: https://github.com/FAIRsharing/FAIRsharing-API/pull/550
The server-side code is fine, but I'm not particularly happy with the client-side stuff in this PR. I wasn't able to test one function and so I can only think to miss it out and create another ticket for someone competent in Javascript to look at the TODOs in the code later, to refactor and test properly. 
Of course, simply trying it out in a browser produces the expected result, despite the minimal automated testing.

### CODE REVIEW

**Review by ramGranell — COMMENTED** [review]
I try to run in netlify and it is given the following error in the console when pressing the download button:
vue.runtime.esm.js:1897 TypeError: Cannot read properties of undefined (reading 'slice')
    at SummaryDownload.vue?74b6:77:1
    at u (runtime.js:63:40)
    at Generator._invoke (runtime.js:294:22)
    at Generator.next (runtime.js:119:21)
    at n (asyncToGenerator.js:3:20)
    at a (asyncToGenerator.js:25:9)
    at asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at asyncToGenerator.js:21:12
    at s.commenceDownload (SummaryDownload.vue?74b6:75:1)

**Comment by knirirr** [comment]
I've not seen anything of that sort. What was the URL of your search?

**Comment by ramGranell** [comment]
> I've not seen anything of that sort. What was the URL of your search?

https://deploy-preview-1739--fairsharing.netlify.app/search?fairsharingRegistry=Policy

**Comment by knirirr** [comment]
This was a nuisance related to Netlify only; I have worked around it but the URL in the downloaded file will have to refer to preview.fairsharing.org instead of this build.

**Review by ramGranell — APPROVED** [review]
It seems to work properly, the only thing is that the file took almost 1 minute to be generated to be downloaded (it was a big one as it included all the databases). Maybe indicating in some place that the process can take a while can be helpful.

**Comment by knirirr** [comment]
> It seems to work properly, the only thing is that the file took almost 1 minute to be generated to be downloaded (it was a big one as it included all the databases). Maybe indicating in some place that the process can take a while can be helpful.

How would you suggest doing that? I don't have any particular ideas. 
Also, I suspect that delay was not time taken to create the file, but for the API to restart (a repeat of the attempt may well be faster).

**Comment by ramGranell** [comment]
> > It seems to work properly, the only thing is that the file took almost 1 minute to be generated to be downloaded (it was a big one as it included all the databases). Maybe indicating in some place that the process can take a while can be helpful.
> 
> How would you suggest doing that? I don't have any particular ideas. Also, I suspect that delay was not time taken to create the file, but for the API to restart (a repeat of the attempt may well be faster).

You can simply add something in the information that appears when the cursor is over the Download button? At the moment, it says "Download a summary of the records show below.", and it can say "Download a summary of the records show below. It can take several seconds."

**Comment by allysonlister** [comment]
The spreadsheets look great, and I like the addition of the search string - thank you!

I tried the following downloads:

* https://deploy-preview-1739--fairsharing.netlify.app/search?fairsharingRegistry=Policy : downloaded quickly. The search results page says 157 records, and the spreadsheet contains 164 records. Could this be something to do with hidden / deprecated resources being shown in the spreadsheet but not the search results, for instance? I'm looking to just exactly replicate the 157.
* https://deploy-preview-1739--fairsharing.netlify.app/search?fairsharingRegistry=Database : took about 1:30 to download, which isn't a big issue for me at all :). search results say 1874 records, spreadsheet has 1910 records.

I'll continue testing once the counts are resolved :)

In response to @ramGranell's comment about warning about large files - I'll add something to the relevant page of gitbook that describes this feature, and how you have to be logged in, and that it uses "|" as a delimiter, and how it could be large for big search results.

Does that sound OK?

Thanks!

**Comment by knirirr** [comment]
> I'll continue testing once the counts are resolved :)

I mentioned this in the comment to the other PR:

https://github.com/FAIRsharing/FAIRsharing-API/pull/550#issue-1288855946

Gitbook sounds like reasonable place for any information for users about this feature.

**Comment by allysonlister** [comment]
Thanks for pointing me to that comment!

I expect others than me will have that question, but I can table it if you will look into it as you have time?

All downloads seem to be working as expected; I have tried a number of additional ones.

**Comment by allysonlister** [comment]
I just noticed that there is a space before each column title other than the very first column title. Please could we remove that?

Thanks!

**Comment by allysonlister** [comment]
BTW I have put some additional documentation at the bottom of this page, and will update the image once the code is completed and merged. I don't mind if, for a little while, we have documentation on a feature that isn't quite available yet ;-)

https://fairsharing.gitbook.io/fairsharing/how-to/search

Please feel free to update it as required!

**Comment by knirirr** [comment]
Some further comments here: https://github.com/FAIRsharing/FAIRsharing-API/pull/552

**Comment by allysonlister** [comment]
[fairsharing_download_1657186266.csv](https://github.com/FAIRsharing/fairsharing.github.io/files/9062221/fairsharing_download_1657186266.csv)

In the attached file, it has 124 rows of records, but the search results say 123. I thought you had found a way around this? Could it be to do with user permissions (e.g. there might be a hidden record in the one I downloaded?)

Thanks!

**Comment by knirirr** [comment]
> In the attached file, it has 124 rows of records, but the search results say 123. I thought you had found a way around this? Could it be to do with user permissions (e.g. there might be a hidden record in the one I downloaded?)

The file has 125 lines: 123 records + 2 header lines.
There may still be discrepancies from time to time but I've done all I can.

**Comment by allysonlister** [comment]
Thanks, and no worries. Indeed, a `wc -l` results in 125 lines, however Libre Office insists on 126. I presume it's some counting issue (or some issue with my brain) but I can't see where. I'm happy enough - thank you!

**Pull request merged**
