### PR TITLE
adding CuratorCohorts page

### PR DESCRIPTION
**Pull request by prakhyatox**
Ticket: https://github.com/FAIRsharing/fairsharing.github.io/issues/1781

WDID:
Added a new page -- CommunityCohorts list by year

Previous PR: https://github.com/FAIRsharing/fairsharing.github.io/pull/1789

### CODE REVIEW

**Comment by prakhyatox** [comment]
1) First draft is ready. Please verify ```https://deploy-preview-1830--fairsharing.netlify.app/community_curation/2022```
and let me know the feedback.

2) There is json data in the page as now just for reference. I will be removing it in the final push

**Comment by knirirr** [comment]
The code seems fine to me. I don't have any particular thoughts on the layout, though; that is probably best left to @allysonlister to comment.

**Comment by allysonlister** [comment]
Thanks! In [this comment](https://github.com/FAIRsharing/fairsharing.github.io/issues/1781#issue-1324947969) you can see how I'd like this to work. The following items are mainly based around that:

1. Please can the tiles have less padding between them - they should look more like a cohesive unit
2.  The "Meet [Name]" is great, but should link to the curator's user page on FAIRsharing instead of ORCID
3. the "+" that we can add in the top right corner can flip the curator's square from their logo/photo to the list of their socials and their years active. This is where any socials they've provided, such as LinkedIn or Twitter, can be put as well as their ORCID. If they have no socials, then this will just show their ORCID profile icon/link. For now, everyone's active year is 2022, but we should be able to have that info on our site too. (It will be relevant to pushing to ORCID profiles in future in any case.)
4. All of our Early Adopters should have the phrase "Early Adopter" above the "Organisation" line in their little square. You can find the list of them on community_curation

With respect to the community_curation page, you can replace this sentence and the table that follows it with this text:

> Our user community is diverse in breadth and scope, with a number of [stakeholder groups](https://fairsharing.org/stakeholders)  across all areas of research and research support. In early 2022, we began with a few Early Adopters, who have contributed greatly to the initial success of the programme, and we now have our first full Intake of community curators. Our full [list of community curators](https://fairsharing.org/community_curation/2022) shows the breadth and diversity of research areas within the programme.

We might need to revisit the year part of the URL, as it would be great to be able to filter the static page based on the year of interest (currently only 2022).

**Comment by prakhyatox** [comment]
@allysonlister Could you please elaborate the last line of the comment https://github.com/FAIRsharing/fairsharing.github.io/pull/1830#issuecomment-1245285674 ```We might need to revisit the year part of the URL, as it would be great to be able to filter the static page based on the year of interest (currently only 2022).```

**Comment by allysonlister** [comment]
Of course, @prakhyatox - sorry it wasn't clear!

The url you currently use for the 2022 intake (community_curation/2022) is nice, if we decide we want separate pages for each year's intake. However, I was wondering if it might be more helpful to have all of the community curators listed on a single page, and allow the user to filter based on a few different fields.

So, let's imagine we call the page you're making community_curation/our_curators instead. Then, we show all community curators from all years (though I admit we only have 2022 right now!), but have buttons to click to allow people to filter based on e.g.

* year (e.g. buttons for 2022, 2023). Community curators who stay with us more than a year could have multiple years tagged against their profile.
* status (current - which would be equivalent to whatever is the current year, and alumni - which is anyone who is not tagged with the current year)

Does this make more sense?

**Comment by prakhyatox** [comment]
Closing this PR due to a lot of rebasing and merge conflicts. New PR is created for the same ticket https://github.com/FAIRsharing/fairsharing.github.io/pull/1831

**Pull request closed without merging**
