### PR TITLE
Changed URLs to download PDFs instead of loading page. #2070

### PR DESCRIPTION
**Pull request by knirirr**
This completes #2070.

### CODE REVIEW

**Review by ramGranell — APPROVED** [review]

**Comment by allysonlister** [comment]
it looks like the link for the funders actually downloads the researchers factsheet?
image

**Comment by knirirr** [comment]
I don't know. Please would you paste the link you'd like here and I'll sort it out - thanks.

**Comment by allysonlister** [comment]
Full instructions as to how to get the download URLs provided in #2070. 

should be https://zenodo.org/record/7737552/files/FAIRsharing%20for%20you_%20funders%20V1.0.pdf?download=1 but please check.

**Comment by knirirr** [comment]
Yes, those are the instructions I followed.
I am unable to perceive any mistake, so I suggest that I go ahead and merge.

**Comment by allysonlister** [comment]
All I'm saying is that when I click on the hyperlink in the funder box, it goes to 

https://zenodo.org/record/7733026/files/FAIRsharing%20for%20you_%20researchers%20V1.0.pdf?download=1

But it should go to: https://zenodo.org/record/7737552/files/FAIRsharing%20for%20you_%20funders%20V1.0.pdf?download=1

Once that is changed, I am happy to approve. If I am the only one experiencing this, please let me know !

**Comment by knirirr** [comment]
Ah, thanks for the clarification. I can change that easily enough and will do so now.

**Review by allysonlister — APPROVED** [review]
thank you! :)

**Pull request merged**
