### PR TITLE
Added Orcid ID and Twitter username to user edit form #1069.

### LINKED ISSUE #1069: Enhancement: User profile edit form missing orcid and twitter handle
**Describe the bug**
Although I realize that username, orcid and twitter handle are all fields that are not editable for our users, it looks odd that some non-editable profile fields are missing (orcid and twitter handle) while another non-editable field (username) is present and greyed out. It would be nice to be consistent, and to provide a short explanation of how a user might get in touch if they have questions about their orcid/twitter/username.

As I understand it, these would be greyed out as they might be used as the method of creating a login to FAIRsharing. For instance, if a user made a login using Orcid, we wouldn't want them changing it. However, if they made a "plain vanilla" FAIRsharing account, how can they go back and add their Orcid?

**To Reproduce**
1. Go to https://dev--fairsharing.netlify.app/?#/accounts/profile
2. Click on the burger and choose "Edit Profile"
3. See that orcid and twitter are missing

**Expected behavior**
At a minimum, all profile fields should be visible in the Edit form, although those that the user should be stopped from editing can appear greyed out, as is currently done with username. Additionally, a sentence should be added above the "Edit Profile" button that states: If you would like to request an update to any non-editable profile fields, please get in touch". The "get in touch" part should have a mailto: to contact@fairsharing.org.

If it isn't to involved, it would be good to allow orcid/twitter updates whenever the account was created by other means.

Please let me know if I am misunderstanding how user authentication works, thanks!

**Screenshots**
profile-edit

**Operating system and browser version**
Ubuntu with Firefox 89.0 (64-bit)

### PR DESCRIPTION
**Pull request by knirirr**
You should now be able to change your Twitter handle and ORCID ID by editing your "user profile".

### CODE REVIEW

**Review by ramGranell — COMMENTED** [review]
I tried to update my orcid number and twitter and the changes seem not be saved.
About the phrase"If you would like to request an update to any non-editable profile fields, please get in touch." can you also put directly the email address "contact@fairsharing.org" as there are many people that do not have configured the email server and want to copy the email address to their email application.

**Comment by knirirr** [comment]
> I tried to update my orcid number and twitter and the changes seem not be saved.

They definitely weren't, but now will be as I have pushed a small change to the server.

> About the phrase"If you would like to request an update to any non-editable profile fields, please get in touch." can you also put directly the email address "[contact@fairsharing.org](mailto:contact@fairsharing.org)" as there are many people that do not have configured the email server and want to copy the email address to their email application.

Right click -> "copy email address" takes care of this.

**Comment by ramGranell** [comment]
I manage to break it when modifying my orcid (I put four 9s as the last number) and in console it says: "pub.orcid.org/v2.0/0000-0001-9572-9999:1 Failed to load resource: the server responded with a status of 404 ()". I cannot edit again my user profile.

**Comment by knirirr** [comment]
> I manage to break it when modifying my orcid (I put four 9s as the last number) 

The user display page (which I haven't touched) appears to have some code which displays publications, and which breaks if a non-existent ORCID is saved to the record.

**Comment by ramGranell** [comment]
> > I manage to break it when modifying my orcid (I put four 9s as the last number)
> 
> The user display page (which I haven't touched) appears to have some code which displays publications, and which breaks if a non-existent ORCID is saved to the record.

And there is not any way that if I put a number incorrectly not breaking the edit profile (e.g. a previous check that the status is correct before saving it)? Do you want I open a new ticket about it as this is not the issue of this ticket

**Comment by knirirr** [comment]
> Do you want I open a new ticket about it as this is not the issue of this ticket

I might as well fix it here. It will probably take a couple of hours. 

Edit: That was optimistic.

**Review by hoseinmirian — APPROVED** [review]

**Pull request merged**
