### PR TITLE
Allow organisations to be downloaded in csv #2362

### LINKED ISSUE #2362: Organisations in search results download
This ticket is for the client-side changes required for https://github.com/FAIRsharing/FAIRsharing-API/issues/1007

### PR DESCRIPTION
**Pull request by knirirr**
This allows users to choose to include organisation information in a downloaded file.

Running it in a netlify build will require https://github.com/FAIRsharing/FAIRsharing-API/pull/1013 to be deployed on the development server, which is currently occupied by another branch.

### CODE REVIEW

**Comment by allysonlister** [comment]
Is this PR running properly at the moment? I tried downloading with organisations all polices, to test the timing (https://deploy-preview-2363--fairsharing.netlify.app/search?fairsharingRegistry=Policy) but there appears to be nothing happening after a few minutes.

Similar thing when I try a smaller query, e.g. https://deploy-preview-2363--fairsharing.netlify.app/search?q=multi%20omics

I'm on Firefox/ubuntu, though Chromium also appears to not be downloading.

thanks!

**Comment by knirirr** [comment]
@allysonlister https://github.com/FAIRsharing/FAIRsharing-API/pull/1013 needs to be dealt with first.

**Comment by allysonlister** [comment]
Ok I'll wait until you say before I check this ticket.

**Comment by knirirr** [comment]
It's ready - I have added you as a reviewer.

**Comment by allysonlister** [comment]
image
This is what the downloaded content (the organisation columns) look like. The data itself looks correct, but note that the "Role" column is empty, and I'm not sure what would go there? 

I suggest 

- [ ] replacing the column header "Type" with "Org Relationship Type"
- [ ] Removing the "Role" column
- [ ] Shifting the Search URL (and the URL itself) in some way so you are able to have a column header for "Organisation Name"
- [ ] Adding a column after organisation name called "Organisation URL" for the FAIRsharing organisation url

Thanks!

**Comment by knirirr** [comment]
Somehow the data have become shifted along by a column. 
So, "type" is the type of organisation, and this is present but shifted left when it should be under the role column. 
These are all server-related changes I'll look at shortly.

**Review by allysonlister — APPROVED** [review]
looks great thank you!

**Pull request merged**
