### PR TITLE
Deals with tickets #424 and also #396.

### PR DESCRIPTION
**Pull request by knirirr**
The tickets mentioned refer to:
#396: Merging grants and organisations. A bit vague, but I presume it means putting the funding grant next to each funding organisation, instead of having a separate grants section.
#424: A ticket which @terazus didn't get time to complete (see https://docs.google.com/document/d/1Xqzz1ivAIwmmlH3YGVcoSAh0LRADHvsoNSLVJMRc0I8/edit#) where users requested that organisation types were omitted if missing, instead of having a "not found".

### CODE REVIEW

**Review by ramGranell — APPROVED** [review]
It seems to work properly. The only comment is that sometimes the organisation type is divided into two lines and I don't know if this is desirable (mandatory break line?). It can be seen in https://deploy-preview-425--fairsharing.netlify.app/#/1444 with organisation: ]
National Institutes of Health (NIH), Bethesda, MD, USA (Government 
body)

**Comment by knirirr** [comment]
Looks fine on my screen, but that is fairly large. I have to adjust the browser size to see the line break, which doesn't look too bad to me.

**Comment by hoseinmirian** [comment]
@knirirr may I know why some of the icons regarding funding are not money icon?
image

**Comment by knirirr** [comment]
Yes; there are tooltips on the icon to explain that.

**Review by hoseinmirian — APPROVED** [review]

**Review by terazus — APPROVED** [review]

**Pull request merged**
