### PR TITLE
adding new Statistics Block

### PR DESCRIPTION
**Pull request by prakhyatox**
Ticket
https://github.com/FAIRsharing/fairsharing.github.io/issues/1753

WDID:
Added new StatisticsBlock.vue component to show the analytics data

### CODE REVIEW

**Comment by prakhyatox** [comment]
Please verify the initial layout of the statistics block as per https://github.com/FAIRsharing/fairsharing.github.io/pull/1808#issuecomment-1233113688

https://deploy-preview-1823--fairsharing.netlify.app/

If this is as per the expectations, I will add backgrounds to the cards

**Review by knirirr — CHANGES_REQUESTED** [review]
Looks good to me, though I added a small amount of code to a test so that global.document is available; once that's approved and merged to this one then this should be fine to merge to dev.

**Review by allysonlister — APPROVED** [review]
Looks great, thank you!

**Comment by prakhyatox** [comment]
> Looks good to me, though I added a small amount of code to a test so that global.document is available; once that's approved and merged to this one then this should be fine to merge to dev.

I have fixed the issue https://github.com/FAIRsharing/fairsharing.github.io/pull/1824.
Should not require the above PR.

**Review by knirirr — APPROVED** [review]

**Comment by prakhyatox** [comment]
I have added the images to block. Please let me know if the images are appropriate

**Comment by knirirr** [comment]
The images look fine to me, though @allysonlister may wish to comment (and/or show them to Susanna).

**Comment by allysonlister** [comment]
Hi all!

I've talked with Susanna - she likes the new counters a lot, but preferred the version before without the images, just the number, title and descriptive text.

She also suggests the following order and slight tweak to the text I made ;-)

From left to right:

Records
Descriptions of standards, databases and policies

Contributors
Our community of record maintainers and curators

Views
Page visits since 2015


Thank you!

**Pull request merged**
