### PR TITLE
Communities 1927

### PR DESCRIPTION
**Pull request by knirirr**
This is not yet ready for review; once https://github.com/FAIRsharing/fairsharing.github.io/issues/1927#issuecomment-1372130362 has been resolved we can proceed with modifying this branch accordingly.

### CODE REVIEW

**Comment by allysonlister** [comment]
Thanks for this! While I'm aware this is not ready for review yet, it is looking good and I will start contacting a few selected tools that make use of FAIRsharing so we can launch this with some real content.

In the meantime, please would you make the following updates to the text I've asked you to add in https://deploy-preview-1984--fairsharing.netlify.app/communities ?

1. I made a mistake in my [original comment](https://github.com/FAIRsharing/fairsharing.github.io/issues/1927#issue-1466602186) where I said the "Organisations" link should go to the first table - it should, in fact, be an internal link to the third table. I've updated the comment accordingly, and please could you update the static page?
2. Could the section that currently looks like this:
image
 instead be a series of buttons that stretch across a single line of the page, to make them stand out?
3. Could each of these new subsections have a subsection title in the same way "Adopters" is, but in a smaller size?
Thanks!

**Comment by allysonlister** [comment]
Oh, and also, the new tiles for the tools look great, but it doesn't seem as though they have all of the information yet. There is a placeholder for a description, but not for the other fields (method of use, type of resource, status of integration). I'm happy for you to explore options about how to show this, but perhaps some sort of tags in the same way as we have for the Early Adopters in the community curators?

**Comment by allysonlister** [comment]
Thank you! some comments:

1. I've asked @proccaserra to provide a better image for FAIRcookbook - I wonder if he accidentally uploaded the wrong one.
2. We need a way to also show the tool in use if any of our form submitters choose to upload such a screenshot. Perhaps if they click on the tile? I can provide such a test screenshot for FAIR cookbook below, which shows a link through to FAIRsharing
3. The homepage for the tool is missing - perhaps hyperlink the name of the tool?
4. For some reason there is no email associated with the FAIR cookboook tile?

Otherwise looking good! Thanks!

image

**Comment by knirirr** [comment]
(1) Thanks.
(2) I'm afraid I don't have any ideas for that at present. 
(3) I've added a link to the tool name (a typo had caused the link to go missing). 
(4) None was provided in the contact information.

**Comment by allysonlister** [comment]
Thanks!

In relation to item 2, perhaps you can ask Prakhat or Dom for advice?
In relation to 4, I agree this is an issue - because we tried to consolidate name, contact email and organisation to have fewer form items, it leaves us open to this kind of issue. However, we said we'd use all fields publicly unless otherwise specified, so this information:

image

Can be used. In this particular case, let's presume @proccaserra missed out this info accidentally, and please use fairplus-cookbook@elixir-europe.org which is their official contact email.

Thanks!

**Comment by allysonlister** [comment]
Also, there seems to be some kind of colour filter on the logos, making them look darker than they are originally. Can that be looked into please?

**Comment by knirirr** [comment]
> Also, there seems to be some kind of colour filter on the logos, making them look darker than they are originally. Can that be looked into please?

Indeed. Here it is:

https://github.com/FAIRsharing/fairsharing.github.io/blob/communities_1927/src/views/Static/Community/Community.vue#L305

Without it, the text is very hard to read.

**Comment by allysonlister** [comment]
That makes sense. Is it possible to apply a vertical gradient of some kind as well, so that as you go "up" to the top of the tile, the dark bit disappears? Sorry that I am not wording it correctly...

**Comment by allysonlister** [comment]
This is looking good thanks - looks like you still need to add the cookbook email (see above) but otherwise I think this is good for now. If you ever have any other ideas about the gradient, please feel free to implement them!

**Comment by allysonlister** [comment]
image_2023_02_09T22_25_18_771Z
Here is the image Dom provided for FAIR cookbook. Once that is done, and the cookbook email (see above) has been added, I'm happy to approve this - thanks!

**Review by allysonlister — APPROVED** [review]
Looks great! We can add it and then encourage more people to reply to the form :) Thanks!

**Pull request merged**
