### PR TITLE
Adding new tools #2027

### PR DESCRIPTION
**Pull request by ramGranell**
Here are the new tools information:
https://deploy-preview-2032--fairsharing.netlify.app/communities#tools

### CODE REVIEW

**Review by knirirr — CHANGES_REQUESTED** [review]
I suggest adjusting height at https://github.com/FAIRsharing/fairsharing.github.io/blob/master/src/views/Static/Community/Community.vue#L326 until the text for the DSW is accommodated.

**Comment by allysonlister** [comment]
image


Thank you! Some notes:

1. Charles has asked that we also add Harvard Medical School to the list of organisations for the bio.registry. Please can you do that?
2. there is some wrapping/overspill on the DSW tile
3. RDMkit and FIPwizard's logos look a bit odd, as you can't see most of them. Perhaps if they don't look good when put into the tile, you can try adding some padding around the image in order to show it better? Alternatively, check the form responses as often they say that they can provide alternative icons if those don't work; or, email the tool devs and ask for a different shape of icon. In the meantime we can progress with these icons, but this is something you can check before asking for review, in general :)
4. Both DSW (I think?) and FIP wizard have provided screenshots of the tool in action. is this work part of this ticket, or will be done separately?
5. the URL that is shown when I click on the Tools button is still https://deploy-preview-2032--fairsharing.netlify.app/communities# and not communities#tools
6. We need a way to communicate the new anchors for each tile to our 3rd-party devs. Perhaps an addition to each tile that just says "link to this tile" or similar? Is that part of this ticket, or not?

Thanks!

**Comment by knirirr** [comment]
Point no. 4 will have to be a separate ticket at a later date. 
Point no. 5 shouldn't be addressed here - I need to find time to look at it. 
Point no. 6 will need a separate ticket.

**Comment by allysonlister** [comment]
Thanks - after 1-3 are dealt with please let me know and I'll review again.

**Comment by ramGranell** [comment]
> Thanks - after 1-3 are dealt with please let me know and I'll review again.

1-2 are performed and emails were sent (FAIRsharing account) asking for square logos for 3.

**Comment by knirirr** [comment]
It looks like that DSW box needs a bit more height still.

**Comment by allysonlister** [comment]
I agree with @knirirr that a bit more space might be needed for the DSW tile.

and separately, before closing this ticket, please make sure appropriate new tickets are made (as necessary) for the other items, thanks. https://github.com/FAIRsharing/fairsharing.github.io/issues/2030 already exists for item 6, the other two may already be parts of existing tickets?

**Review by knirirr — APPROVED** [review]

**Comment by knirirr** [comment]
> the other two may already be parts of existing tickets?

Yes, #1927 and #2030. 

New PRs can be opened when those are addressed; this PR can be closed after merging but not any tickets.

**Review by allysonlister — APPROVED** [review]
thank you!

**Pull request merged**
