### PR TITLE
adding Curators cohort block

### PR DESCRIPTION
**Pull request by prakhyatox**
Ticket: https://github.com/FAIRsharing/fairsharing.github.io/issues/1781

WDID:
Added a new page -- CommunityCohorts list by year

Previous PRs: 

1. https://github.com/FAIRsharing/fairsharing.github.io/pull/1789
2. https://github.com/FAIRsharing/fairsharing.github.io/pull/1830

### CODE REVIEW

**Comment by prakhyatox** [comment]
1) Update the page as comments https://github.com/FAIRsharing/fairsharing.github.io/pull/1830#issuecomment-1245285674
```https://deploy-preview-1831--fairsharing.netlify.app/community_curation/our_curators```
Please verify layout for cards and let me know your feedback

2) Work in progress for comment https://github.com/FAIRsharing/fairsharing.github.io/pull/1830#issuecomment-1245454575

3) Currently, profile images are for reference. Those will be removed before merging

**Comment by allysonlister** [comment]
This is looking amazing! Thank you :) The layout, information in "+", early adopters are all super. I think the only thing remaining is to store and show the years active (and the filtering by year etc as described before).

Great work!

If you can send me the current json for this test data on zulip, I can start populating it with the real information I have, if you like?

**Comment by prakhyatox** [comment]
1) Draft 2 is ready for review as per https://github.com/FAIRsharing/fairsharing.github.io/pull/1830#issuecomment-1245454575

Link: ```https://deploy-preview-1831--fairsharing.netlify.app/community_curation/our_curators```


2) Unit test are failing but will fix it once I get final approval for layout.

**Comment by allysonlister** [comment]
All of the layout that is present is perfect, no modifications required!

Please can you add a field in the white section within each rectangle with "Years active: " - all will currently have the value of 2022, but e.g. next year, some will have just 2022, and others will have "2022, 2023" or "2023". This will have a visible acknowledgement of activity, and allow us to filter later on.

Thanks!

**Comment by prakhyatox** [comment]
Final push is done. PR is ready for review and merge

**Comment by allysonlister** [comment]
Fantastic! Looks like you've already got a list of all of the early adopters with "real" data - here is the short file I've been working on that includes them and our first of the current intake, Gabriel Pelletier. You may wish to merge this information against what you have (in some cases you have more info than I have below), and add Gabriel please.

```json
[
  {
"name": "Lindsey Anderson",
"id": 5015,
"organisation": "PNNL",
"id_organisation": 2284,
"scope": "Omics",
"early_adopter" : true,
"show_more" : false,
"orcid": "0000-0002-8741-7823",
"twitter": "lnanderscience",
"linkedin" : "lnanderscience"
},
  {
"name": "Kyle Copas",
"id": 5832,
"organisation": "GBIF",
"id_organisation": 1166,
"scope": "Biodiversity",
"early_adopter" : true,
"show_more" : false,
"orcid": "0000-0002-6590-599X",
"twitter": "kylecopas",
"linkedin" : "kylecopas"
},
{
"name": "Annie Elkjær Ørum-Kristensen",
"id": 6182,
"organisation": "GBIF",
"id_organisation": 1166,
"scope": "Biodiversity",
"early_adopter" : true,
"show_more" : false,
"orcid": "0000-0002-8326-5789"
},
  {
"name": "Gabriel",
"id": 7670,
"organisation": "McGill University",
"id_organisation": 1802,
"scope": "Neuroscience",
"early_adopter" : false,
"show_more" : false,
"orcid": "0000-0003-3257-0545",
"twitter": "neuropelletier"
},
  {
"name": "Joe Miller",
"id": 6118,
"organisation": "GBIF",
"id_organisation": 1166,
"scope": "Biodiversity",
"early_adopter" : true,
"show_more" : false,
"orcid": "0000-0002-5788-9010"
},
  {
"name": "Malin Sandström",
"id": 464,
"organisation": "Karolinska Institutet, INCF",
"id_organisation": 1321,
"scope": "Neuroscience",
"early_adopter" : true,
"show_more" : false,
"orcid": "0000-0002-8464-2494"
}
]
```


A few final changes now that I'm looking at the live site please:

1. on https://deploy-preview-1831--fairsharing.netlify.app/community_curation please remove the table of early adopters. Now that we have the link to the full list of curators, we don't need the old table as well. 
2. To draw attention to our full set of curators, please add some kind of centered logo/button/title just below the heading "Our Community Curators" and before the text that is currently in that section. Happy for  you to push this item into a separate ticket as it doesn't have a great bearing on the success of this ticket.
3. Clicking on "Alumni" results in a 404, presumably because we have no alumni yet. can an empty page be shown instead?
4. You're right that just having "Alumni" or "Current Curators" might be confusing. Sorry I didn't see that when you pointed it out. Please could you change those buttons to "View Alumni" and "View Current Curators"?
5. When the Orcid is displayed, you are showing the little orcid icon followed by the word "Orcid". Please would you modify that so it also shows the actual orcid instead? People will know from the icon and the orcid itself the type of identifier it is, so we don't need the word "orcid".

**Comment by prakhyatox** [comment]
1) Added new curator data as per json in comment https://github.com/FAIRsharing/fairsharing.github.io/pull/1831#issuecomment-1253582126

2) All points are addressed and updated

3) For point2 in comment https://github.com/FAIRsharing/fairsharing.github.io/pull/1831#issuecomment-1253582126
 ```To draw attention to our full set of curators, please add some kind of centered logo/button/title just below the heading "Our Community Curators" and before the text that is currently in that section. Happy for you to push this item into a separate ticket as it doesn't have a great bearing on the success of this ticket.``` 
separate ticket needs to be created to address the change

**Comment by knirirr** [comment]
This looks good to me.
Only one thing I didn't expect, which is the organisation name on each curator's record not being a link to our page for that organisation; I don't know if that has already been discussed and decided against, though.

**Review by knirirr — APPROVED** [review]

**Comment by allysonlister** [comment]
Thanks for spotting that Milo.

The json includes an organisation id as far as I'm aware, so let's have a link from the organisation name to our organisation page please, then we can close this.

thanks!

**Review by allysonlister — APPROVED** [review]
thank you!

**Comment by allysonlister** [comment]
I'll check this tomorrow then... I thought the organisation link clicked through to our organisation page as well. My mistake if I didn't catch it before!


--

Dr. Allyson Lister

FAIRsharing Coordinator - Content & Community


Oxford e-Research Centre, University of Oxford

Data Readiness Group: https://datareadiness.eng.ox.ac.uk/


ORCiD: 0000-0002-7702-4495
@allysonlister

Please note that I work part time. If the matter is urgent, you may wish to email ***@***.******@***.***> instead.


For more on FAIRsharing, please see https://fairsharing.org<https://fairsharing.org/>

________________________________

**Pull request merged**
