### PR TITLE
fixing RelatedContent search duplicate

### LINKED ISSUE #1525: Searching for relationships in a record view only returns one of them, not all
**Describe the bug**
our relationship search within our record view, shown at the end of the animation, only displays one of the two relationships that were added. However, if you manually scroll (see screenshot below), both relationships are present.

**To Reproduce**
1. Go to https://preview.fairsharing.org/2163 and https://preview.fairsharing.org/2294
2. note error when searching database relationships

**Expected behavior**
using the search box to filter database relationships (and other relationships too!) should return all relationships between the two resources and not just one of them

**Screenshots**
both relationships are present in both records (to each other)
obis2

but only 1 is shown in the search
only1

**Operating system and browser version**
Firefox / ubuntu

### PR DESCRIPTION
**Pull request by hoseinmirian**

### CODE REVIEW

**Comment by hoseinmirian** [comment]
if there is a duplicate or more record with the same name and id then their label like 'related to' and any more will be separated by and and will be shown to user. 

It will also takes care of the search problem cz there was multiple item with the same reference before with different labels. now they are all merged into one with multiple labels. 
image

image

image


and with search it will only find one item which is what we want!
image

**Comment by hoseinmirian** [comment]
@allysonlister and @knirirr please let me know if you're happy with this based on the screenshot I provided so I can start writing the test. thanks

**Comment by allysonlister** [comment]
The screenshots look good. Please could you provide an additional screenshot that shows how this looks from the view of the other record (Ocean Biodiversity Information System)? Thanks!

**Comment by hoseinmirian** [comment]
@allysonlister other record
image

image

**Comment by allysonlister** [comment]
One last thing I just noticed, and then I will approve, thank you.

When you join the two "hover-over" sentences, please can you make the second sentence begin with a lowercase letter? In the examples above, the second "This" should be "this", i.e. "...and this resource is..."

Thanks!

**Comment by knirirr** [comment]
I tried this out on https://deploy-preview-1539--fairsharing.netlify.app/2163 and found the following, i.e. there should be two hits but only one is seen when "searching".
Screenshot 2022-02-16 at 11 28 06
Screenshot 2022-02-16 at 11 28 22

There appears to be a failing test as well:

https://github.com/FAIRsharing/fairsharing.github.io/runs/5211960918?check_suite_focus=true

**Comment by allysonlister** [comment]
@knirirr Hossein has put both relationships into one sentence, to solve this issue.

**Comment by knirirr** [comment]
> @knirirr Hossein has put both relationships into one sentence, to solve this issue.

Thanks; I'd not spotted that (as you may have guessed).
However, there still appear to be test issues with this branch; I get three failures when running `npm run test:unit` locally, for example.

**Comment by hoseinmirian** [comment]
@allysonlister happy? This in the middle turned into this except the 1st one. 

image


@knirirr I  have been working to fit the layout. have not started the test yet.

**Comment by knirirr** [comment]
> @knirirr I have been working to fit the layout. have not started the test yet.

Safest, then, to mark as a draft to avoid confusion.

**Comment by allysonlister** [comment]
Thanks @hoseinmirian . My apologies, but now that I see it with the latest screenshot, please can I suggest another minor modification to the hover over text?

instead of "relation sentence 1 [and] relation sentence 2 [and] relation sentence 3"

please can we have it like this: "relation sentence 1[; ] relation sentence 2[; ] relation sentence 3"

That might be easier to read. Thank you!

**Comment by hoseinmirian** [comment]
looks good?

image

**Comment by allysonlister** [comment]
Once you have removed the space before the ";" it will be just right - thank you!

**Comment by hoseinmirian** [comment]
image

**Comment by allysonlister** [comment]
I'm happy with this! Thanks!

I have not approved as it says some checks aren't successful ...

**Comment by hoseinmirian** [comment]
> I'm happy with this! Thanks!
> 
> I have not approved as it says some checks aren't successful ...

now its ready.tnx

**Review by knirirr — APPROVED** [review]

**Review by allysonlister — APPROVED** [review]
Thank you!

**Pull request merged**
