### PR TITLE
Add loads of extra toggle buttons for nodes. #2060

### PR DESCRIPTION
**Pull request by knirirr**
This implements the functionality requested in #2060, but the button layout for registries is broken on small screens.

### CODE REVIEW

**Comment by knirirr** [comment]
N.B. the current layout represents the limits of what I can do in terms of styling.

**Review by allysonlister — COMMENTED** [review]
Thank you so much for this! I'm using https://deploy-preview-2064--fairsharing.netlify.app/graph/2521 as an example here...
image

The issue here is that all standards in the "2 hop" are still being shown. In this case, what we'd like to see are only those standards linked to whatever has been selected in the "1 hop". Does that make sense? Thanks!

image

**Comment by knirirr** [comment]
Ah, I see. Unfortunately I can't do that. Would you prefer to keep this branch as it is, or discard it and use the graphs as they currently are?

**Comment by allysonlister** [comment]
This is a key feature for our graphs that our users really would like.

Is there any way to traverse a graph that you're displaying in a "live" manner? You are already hiding/showing nodes depending on certain characteristics. Is it possible, even with additional coding, to have a rule that nodes are only shown if they are connected to an already visible node?

**Comment by knirirr** [comment]
We can't generate the graph on the fly and there doesn't appear to be any means of handling this request within the rendering engine, though I have already been investigating it (not quite finished yet). Please think on what you would prefer in the event that this can't be done, no matter how much it is wanted.

**Comment by allysonlister** [comment]
Thank you for investigating, I do hope you can find a solution.

A lengthier option might be pre-computing each of the different options the user might generate (that is a LOT of combinations, I know!) at the same time as you pre-compute each graph already.

**Comment by knirirr** [comment]
Generating multiple graphs will not be feasible, I'm afraid. 
Please let me know your preference for (1) keeping this branch as it is, or (2) discarding it and sticking with the graphs as currently active on the site.

**Comment by allysonlister** [comment]
Let's talk about this in the next dev meeting before making any decisions. Thanks!

**Comment by allysonlister** [comment]
If it cannot be done with this library or codebase, then we cannot use this branch, thanks. We'll still have a chat about longer-term options on Monday, though, as this is a key feature.

Thanks!

**Pull request closed without merging**
