### PR TITLE
Dom search query

### PR DESCRIPTION
**Pull request by terazus**

### CODE REVIEW

**Review by knirirr — CHANGES_REQUESTED** [review]
Other than the close button looking a bit wonky, which I don't know how to fix, It looks good to me.

Screenshot 2020-07-28 at 13 43 13

**Comment by terazus** [comment]
I think this is a CSS issue with all the icons inside fields. The autocomplete from the search panels are also affected.
I think i already addressed this with @hoseinmirian. Do you have a ticket for that hossein?

**Comment by hoseinmirian** [comment]
the reason I used prevent for submitting form is a cliche issue addressed in the below link. @terazus @knirirr 
https://laracasts.com/discuss/channels/vue/atsubmitprevent-or-just-atclick?page=1

**Review by hoseinmirian — APPROVED** [review]
now its fine

**Pull request merged**
