### PR TITLE
Latest re-arrangement of related record display #1584.

### PR DESCRIPTION
**Pull request by knirirr**
As far as I can tell from looking at records and from running the modified unit tests, this will now behave as described here:

https://fairsharing.gitbook.io/fairsharing/associated-records/from-standards-records

If anyone can find any examples where it does not then please note the offending entry, and what you'd expect to see instead, below.

### CODE REVIEW

**Review by ramGranell — COMMENTED** [review]
I haven't checked all the cases but as far as I can see they seem correct.

**Review by ramGranell — APPROVED** [review]

**Review by delphinedauga — APPROVED** [review]
Checked all the relations, ok, thanks !

**Review by allysonlister — CHANGES_REQUESTED** [review]
Thank you. I'm still looking, but have started with a standards record and thought you'd want to know what I've found so far.
Example: https://deploy-preview-1622--fairsharing.netlify.app/1195
allmultiples
Above is a screenshot of the relationships I've added for testing to that record, and you will be able to see them in the edit interface yourself as well.

However, while both relationships to the Plant Phenotype Ontology are shown in the record view, only one relationship to the Minimum Information about GWAS Experiment is shown. I'll report any further inconsistencies as I find them. Thanks!

**Comment by allysonlister** [comment]
I have added a number of relationships to other standards records that link them to https://deploy-preview-1622--fairsharing.netlify.app/1195, and these have also resulted in errors.

Please examine all of the relationships within these two records and note how they are not correctly represented in 1195:
* https://deploy-preview-1622--fairsharing.netlify.app/448
* https://deploy-preview-1622--fairsharing.netlify.app/449

Finally, after adding extra relations from 448 -> 1195 and 449 -> 1195, I noticed the following oddity that hadn't appeared previously:

drao

Note that DRAO (https://deploy-preview-1622--fairsharing.netlify.app/604) is only related to 1195 via "related to", and yet multiple relationships are displayed for that link.

I'll hold off on further checks until these have resolved, as they may well be also happening in the other record types. Thanks!

**Comment by knirirr** [comment]
> Please examine all of the relationships within these two records and note how they are not correctly represented in 1195:

I'm afraid I'm not certain what the issues are.
Are you able to give me any specific examples of a link which is incorrect and what you would consider the correct appearance of that link?

> I noticed the following oddity that hadn't appeared previously

This is strange; I haven't made any changes to the part of the code that handles merging links. I'll look into it whilst I wait for further clarification.

**Comment by allysonlister** [comment]
> I'm afraid I'm not certain what the issues are.
> Are you able to give me any specific examples of a link which is incorrect and what you would consider the correct appearance of that link?

You look at all the relationships each record should have (they appear to all be visible in the Edit Interface), and then compare them to what is displayed in the record View, and check for differences. That is all I would do. I gave you some examples to get started in the screenshot, you just need to continue in that vein. I don't work on Friday and so just sent a few replies to get you started, so you would know there are issues with the relationship display.

Thanks, and have a good weekend!

**Comment by knirirr** [comment]
I've modified the only thing I can see by that obvious method, so I'll re-request review and will get back to this next week, should you notify me of anything specific.

**Comment by allysonlister** [comment]
Thanks! I'm really glad that you can compare the edit and record views, as this is exactly how I've been finding the inconsistencies.

I've found another bug, and will continue checking once that is resolved as they may be related.

As you can see below, the GWAS relationships are only displayed for me when I am logged into the record.
gwas

Let me know once you've got all of the relations in the edit interface and record views to match in the following records, and then I'll continue my tests. Note that I will be unavailable for checking after 6 April.

-  https://deploy-preview-1622--fairsharing.netlify.app/1195
-  https://deploy-preview-1622--fairsharing.netlify.app/448
-  https://deploy-preview-1622--fairsharing.netlify.app/449

**Comment by knirirr** [comment]
Please note that the current production system is not necessarily an example of "correct" behaviour for comparison; the code changed in this commit:

https://github.com/FAIRsharing/fairsharing.github.io/pull/1622/commits/3832647a62b061b6ee19194e64a71d89152f4ebe

Is buggy, and still present in production. 

> Thanks! I'm really glad that you can compare the edit and record views, as this is exactly how I've been finding the inconsistencies.

Please report any that are found with as much detail as possible.
I'll look next at the GWAS record mentioned above.

**Comment by allysonlister** [comment]
I am not working beyond my two meetings today, so I will need you to compare a) the relations displayed in the edit interface to b) the relations displayed record views for the following records, rather than waiting for me to do so, as I will not get to it today (I am only working intermittently this week. Thank you!

- https://deploy-preview-1622--fairsharing.netlify.app/1195
- https://deploy-preview-1622--fairsharing.netlify.app/448
- https://deploy-preview-1622--fairsharing.netlify.app/449

**Comment by knirirr** [comment]
> I've found another bug, and will continue checking once that is resolved as they may be related.
> As you can see below, the GWAS relationships are only displayed for me when I am logged into the record.

Fortunately, this is not a bug. GWAS (440) is hidden and so will only be visible to logged-in curators or the record maintainer; the three relations to this record appear to be correctly suppressed when necessary. 

> https://deploy-preview-1622--fairsharing.netlify.app/1195
> https://deploy-preview-1622--fairsharing.netlify.app/448
> https://deploy-preview-1622--fairsharing.netlify.app/449

I can find no discrepancy between the relations returned from the database and those displayed on the record page for any of these records. 

I'm not sure what you saw that looked out of place, of course, but was it that, for example, that "Observations and Measurements" was not shown in the edit interface when editing record 449? If so then that is expected behaviour as only outgoing relations can be edited. To change incoming relations the linking record must be edited. 

So, everything still looks ready to deploy, as far as I can tell.

**Comment by delphinedauga** [comment]
Hope it could help, I can't see any strange behavior : 
- 1195 <-> 440 ok when logged in, not visible when logged out, normal as 440 is hidden
- 1195 <-> 448
    - Related, profiles, extends, deprecate
    - The 4 relations are on edit from 448
    - Relations are well displayed on frontend 448 and 1115 (logged in or not)
- 1195 <-> 449
    - Related, profiles, extends 
    - The 3 relations are on edit from 449
    - Relations are well displayed on frontend 449 and 1115 (logged in or not)

**Comment by allysonlister** [comment]
Thanks @knirirr for all of your recent comments, good to know that the logged in issue was not an issue at all, just me not noticing the record was hidden.

Thanks also both to @knirirr  and @delphinedauga for checking the standards. I agree that they all look perfect now, thank you.

I'm passing the rest of the review (to check database, collection and policy records) to @delphinedauga as I've run out of time - she will double check when she's next working on FAIRsharing.

**Comment by delphinedauga** [comment]
So I tested relation database <-> standard and I found a strange behavior. 
If i tried to add several relation types from the database record to the standard record at the same time, the display doesn't work -> canSAR (https://deploy-preview-1622--fairsharing.netlify.app/1559) DATABASE ACCEPTS and IMPLEMENTS MIAME standard (https://deploy-preview-1622--fairsharing.netlify.app/FAIRsharing.mrrzb3) : 
Apr-05-2022 20-56-44

The display is also affected on the MIAME standard record  : 
Capture d’écran 2022-04-05 à 21 00 46

When I add one relationship at a time, I have no problem.
When I add at the same time: 
- Implements & accepts (like in the gif) : display fails
- Implements & outputs : display fails
- Implements & related_to : display is ok
- Accepts & outputs : display fails
- Accepts & related_to : display is ok
- Outputs & related_to : display is ok

I can't understand the problem :/

**Comment by knirirr** [comment]
The problem turned out to be that no definitions were provided for "accepts" and "outputs", back when this feature was originally coded.

**Review by delphinedauga — APPROVED** [review]
It seems that now everything is ok, thanks Milo !

**Comment by delphinedauga** [comment]
I also tested relation from collection and policy : nothing weird :)

**Comment by knirirr** [comment]
Thanks, all as expected, then.

**Pull request merged**
