### PR TITLE
Add fairsharing when no abbreviation provided

### LINKED ISSUE #961: when no abbreviation please show "fairsharing"
when no abbreviation please print "fairsharing" in the HTML.

### PR DESCRIPTION
**Pull request by hoseinmirian**
Point 8 in the recently-circulated document.

### CODE REVIEW

**Review by knirirr — CHANGES_REQUESTED** [review]
This seems to fix an issue other than the one requested. Take a look at the tab in the top left, here:

Screenshot 2021-05-24 at 16 18 45

**Comment by hoseinmirian** [comment]
@knirirr it seems ok. I double-checked the result of the record you took a screenshot of. It seems fine. ticket ask to add 'fairsharing' if there are no abbreviation provided. Please correct me if its wrong. tnx
image

**Comment by knirirr** [comment]
You're looking at a different part of the record page:

dodgy_tab

**Comment by hoseinmirian** [comment]
for testing please use:
http://localhost:8080/#/3341
http://localhost:8080/#/FAIRsharing.6k0kwd

**Review by knirirr — APPROVED** [review]

**Pull request merged**
