### PR TITLE
Record count on homepage

### LINKED ISSUE #1288: Searches for front-page "Databases" entry point returns all registries
**Describe the bug**
The URLs for the searches for the "Databases" box on the homepage are incorrect, pointing across all registries rather than databases only.

**To Reproduce**
1. Go to https://beta.fairsharing.org/
2. Scroll down to 'Databases'
4. See error for each of Natural Science, Engineering Science, Social Science, Humanities

**Expected behavior**
These search URLs should be for databases only, not across all of FAIRsharing.

**Screenshots**
databases

**Operating system and browser version**
Ubuntu / Firefox

### PR DESCRIPTION
**Pull request by knirirr**
This deals with the issue in https://github.com/FAIRsharing/fairsharing.github.io/issues/1288 by adding a new route to count number of records which are both databases and have a particular tag (this will not be in the aggregations).
The relevant server changes are on dev-api.fairsharing.org (see https://github.com/FAIRsharing/FAIRsharing-API/pull/364).

### CODE REVIEW

**Review by ramGranell — COMMENTED** [review]
I cannot see anything as it redirects always to: https://deploy-preview-1299--fairsharing.netlify.app/#/maintenance : Maintenance Mode.....

**Comment by knirirr** [comment]
I cannot find any fault on the server but have reloaded Nginx anyway. 
Please try again - thanks.

**Review by ramGranell — APPROVED** [review]
It seems to work properly!!

**Comment by knirirr** [comment]
If there are still no additional reviews by the time I get chance to update this branch I'll merge it anyway.

**Comment by hoseinmirian** [comment]
> If there are still no additional reviews by the time I get chance to update this branch I'll merge it anyway.

I review it now. plz wait.

**Review by hoseinmirian — APPROVED** [review]

**Pull request merged**
