### PR TITLE
Tag capitalisation

### PR DESCRIPTION
**Pull request by knirirr**
This deals with the request in ticket #1260.

### CODE REVIEW

**Comment by allysonlister** [comment]
Thanks!

The record view has now been updated to show appropriate mixed casing. However, I still see the second and later words uppercased for the edit form:
almost

thank you!

**Comment by knirirr** [comment]
I thought the request was that taxonomy tags should be corrected (e.g. "Homo sapiens" instead of "Homo Sapiens") but other tags should be left as they are; only taxonomy tags are mentioned in the ticket. That is what I have done.

**Comment by allysonlister** [comment]
I agree completely - I thought this is what I had asked? In the screenshot, it is the taxonomy tags that are shown (e.g. the various Drosophila species) that still have the second word capitalised. Perhaps I should have circled the relevant bit of the screenshot, apologies...

**Comment by knirirr** [comment]
Thanks. Yes, marking areas of the screenshot is often helpful.

**Review by terazus — APPROVED** [review]

**Pull request merged**
