### PR TITLE
Apply Not available for identical record

### LINKED ISSUE #1395: Allow "Not available" for homepage URL for collections
Some collections will never have a homepage. Therefore, to prevent us simply putting the same value for both homepage and reference URL, please can we have "Not available" as a valid string for the homepage field for collections?

Thanks!

### PR DESCRIPTION
**Pull request by hoseinmirian**
as suggested in the attached ticket, please use this record to test:
http://localhost:8080/3493

now if there is identical home page and reference_url for a record, home page will be Not available and reference_url will be shown.

### CODE REVIEW

**Review by knirirr — CHANGES_REQUESTED** [review]
The example record has a different homepage and reference_url so both should be displayed. 
Further comments are here: https://github.com/FAIRsharing/fairsharing.github.io/issues/1395#issuecomment-1005698942

**Review by allysonlister — CHANGES_REQUESTED** [review]
Thank you. However, in this built it appears that the _homepage_ has been marked as "Not available", when it is supposed to be the _reference URL_ that is displayed as "Not available". See https://github.com/FAIRsharing/fairsharing.github.io/issues/1395#issuecomment-1005698942

(example: https://deploy-preview-1449--fairsharing.netlify.app/3518)

**Review by allysonlister — APPROVED** [review]
The changes seem to be good, and I am approving. However, when looking at one of the collections (https://deploy-preview-1449--fairsharing.netlify.app/3519), for some reason there was a green banner saying that my request to maintain the record has been approved? I am already the maintainer of this record in the live version of the server, so I'm not sure why this banner has appeared in the netlify build. Please investigate and make a new ticket if required.
maintain

**Comment by hoseinmirian** [comment]
> has appeared in the netlify build

so far its been what its been no bug or problem! so if there is a need to change its behavior then please create a ticket please

**Comment by knirirr** [comment]
>  for some reason there was a green banner saying that my request to maintain the record has been approved? I am already the maintainer of this record in the live version of the server, so I'm not sure why this banner has appeared in the netlify build.

Are you able to reproduce it, or has it only appeared once?
If you can reproduce it then I will need to see what is happening between your browser and the server, so we'll have to schedule a call for you to show it to me.

**Review by knirirr — APPROVED** [review]

**Comment by allysonlister** [comment]
> > for some reason there was a green banner saying that my request to maintain the record has been approved? I am already the maintainer of this record in the live version of the server, so I'm not sure why this banner has appeared in the netlify build.
> 
> Are you able to reproduce it, or has it only appeared once? If you can reproduce it then I will need to see what is happening between your browser and the server, so we'll have to schedule a call for you to show it to me.

Yes I am. In that netlify build, whenever I view a collection that is maintained by my user account, the banner is there, even though I added myself as maintainer weeks ago. There are at least a couple like that, including the one I gave as the example above. Thanks!

**Comment by allysonlister** [comment]
happy to have a call so I can share my screen etc. Around until 3pm today :)

**Comment by knirirr** [comment]
> happy to have a call so I can share my screen etc. Around until 3pm today :)

Thanks. Please would you open a ticket for this, as it is a different issue from what's being discussed in this PR; I'll investigate when I have time.

**Pull request merged**
