### PR TITLE
Hossein adding propogation to scroll #562

### LINKED ISSUE #562: adding propogation to scroll
by adding propagation we can impose scrolls to stop scrolling other or parent scrolls after they reached the bottom. 

R&D links:

http://jsbin.com/jivutakama/edit?html,js,output
https://htmldom.dev/create-a-custom-scrollbar
https://binaryify.github.io/vue-custom-scrollbar/en/#wheelspeed-number
https://www.npmjs.com/package/vue2-perfect-scrollbar
https://vuejsexamples.com/a-tiny-vue-directive-that-stop-propagation-scroll-when-edge-reached/
https://jsfiddle.net/voxtobox/9ghLbek8/
https://stackoverflow.com/questions/5802467/prevent-scrolling-of-parent-element-when-inner-element-scroll-position-reaches-t
https://stackoverflow.com/questions/1459676/prevent-scroll-bubbling-from-element-to-window
https://vuejs.org/v2/guide/events.html

### PR DESCRIPTION
**Pull request by hoseinmirian**

### CODE REVIEW

**Review by ramGranell — APPROVED** [review]

**Review by knirirr — CHANGES_REQUESTED** [review]
I see the following when running tests:

```
PASS tests/unit/components/Records/Search/Input/SearchInput.spec.js
  ● Console

    console.error node_modules/vue/dist/vue.runtime.common.dev.js:621
      [Vue warn]: Failed to resolve directive: scroll-stop

      (found in <SearchInput>)
```

...there are quite a few repeats of this.

**Comment by hoseinmirian** [comment]
> 
> 
> I see the following when running tests:
> 
> ```
> PASS tests/unit/components/Records/Search/Input/SearchInput.spec.js
>   ● Console
> 
>     console.error node_modules/vue/dist/vue.runtime.common.dev.js:621
>       [Vue warn]: Failed to resolve directive: scroll-stop
> 
>       (found in <SearchInput>)
> ```
> 
> ...there are quite a few repeats of this.

@ramGranell  successfully could pass the tests while @knirirr is getting an error. My tests are passing as well. @terazus could you please check whether it's breaking your tests or not due to I am getting 2 different answers from other developers. tnx

**Comment by knirirr** [comment]
N.B. this was a fresh install on Linux, but I was able to reproduce the same errors on my Mac.

**Review by knirirr — APPROVED** [review]
I now see no errors in the test, and my Mac seems to be behaving again.

**Review by terazus — APPROVED** [review]

**Pull request merged**
