### PR TITLE
Button get curator summary#1931

### PR DESCRIPTION
**Pull request by ramGranell**
This is related to #1931. To check you need to go to the curator panel and download the file using the button on the bottom that says: "CURATOR SUMMARY STATISTICS"

### CODE REVIEW

**Comment by prakhyatox** [comment]
Please share the button screenshot. 
Since, I am not a curator I cannot see the button. I can only see below item.

Screenshot 2022-11-29 at 15 07 38

**Comment by ramGranell** [comment]
> Details

The server is updated and now it should work

**Comment by prakhyatox** [comment]
Just wondering the summary file is in the .txt extension. Shouldn't is be in .csv or .xlsx extension (excel format) so that it can be easily readable.
Please correct me if I may have missed or not aware of the agreed format.

**Comment by allysonlister** [comment]
image


Do I need to be connected to preview.fairsharing? I don't see it after a force refresh of the production server...

**Comment by prakhyatox** [comment]
Its on netlify link [https://deploy-preview-1932--fairsharing.netlify.app/curator](https://deploy-preview-1932--fairsharing.netlify.app/curator)

**Comment by allysonlister** [comment]
thanks - sorry somehow I missed the link this time!

**Comment by allysonlister** [comment]
image


This is looking great, thanks! Please can you remove the ")" from the final column data? Then I think it's there!

Also, it's not a big deal, but just curious as to why the number of edits in the spreadsheet (e.g. 13 for user 7663) are different from the number of edits in the user profile under Record Edits (https://fairsharing.org/users/7663). I presume most of it is because we are splitting out edits and creation events, correct? On the user profile page in the example, there are 14 update events and 4 create events. However, even so, the spreadsheet has 13 updates and the user's profile has 14... Can you tell why this might be the case?

Thanks!

**Comment by ramGranell** [comment]
> image
> 
> This is looking great, thanks! Please can you remove the ")" from the final column data? Then I think it's there!
> 
> Also, it's not a big deal, but just curious as to why the number of edits in the spreadsheet (e.g. 13 for user 7663) are different from the number of edits in the user profile under Record Edits (https://fairsharing.org/users/7663). I presume most of it is because we are splitting out edits and creation events, correct? On the user profile page in the example, there are 14 update events and 4 create events. However, even so, the spreadsheet has 13 updates and the user's profile has 14... Can you tell why this might be the case?
> 
> Thanks!

Parenthesis are removed from the text file. About the counting it is only that you are seeing different databases. In the dev DB there are 13 changes, e.g. https://deploy-preview-1932--fairsharing.netlify.app/users/7663 meanwhile in the production DB there are 14 changes. Obviously, when the branch will be merged to master and code running in production, you will obtain the data from the production DB.

**Review by allysonlister — APPROVED** [review]
thanks, looks great!

**Comment by ramGranell** [comment]
> Just wondering the summary file is in the .txt extension. Shouldn't is be in .csv or .xlsx extension (excel format) so that it can be easily readable. Please correct me if I may have missed or not aware of the agreed format.

As the user of file seems to be happy with the file extension, I think I will keep as it is. It is neither a .csv nor a .xlsx, then being .txt you can open with any editor.

**Review by prakhyatox — APPROVED** [review]

**Pull request merged**
