### PR TITLE
Mt refactoring organisations 324

### PR DESCRIPTION
**Pull request by knirirr**

### CODE REVIEW

**Comment by terazus** [comment]
I think Hossein has already merged that into his own branch.
@hoseinmirian please confirm?

**Comment by hoseinmirian** [comment]
> 
> 
> I think Hossein has already merged that into his own branch.
> @hoseinmirian please confirm?

I merged it before. @knirirr don't know if there is any extra code in it comparing to one I merged?

**Comment by knirirr** [comment]
I have merely added the new code for #340, of which there wasn't much, so I am surprised that more changes are showing up. 

Edit: Just pulled new-layout-design and it doesn't include some of my recent changes, e.g. the "none found" fields.

**Comment by terazus** [comment]
Your previous changes were merge to Hossein-general, not new layout design. So you need to pull from Hossein general and make your PR to that branch.

**Comment by knirirr** [comment]
I'll replace this PR with another, then.

**Pull request closed without merging**
