### PR TITLE
Hossein redesign cartoons #1200

### LINKED ISSUE #1200: Updating cartoons in home page
this task aims to redesign the home page svg slider items ..

### LINKED ISSUE #1206: Update existing icons with better quality
current icons are pngs and this task was created to design icons in Adobe illustrator so we can have svg files.

### PR DESCRIPTION
**Pull request by hoseinmirian**

### CODE REVIEW

**Comment by hoseinmirian** [comment]
@knirirr this ticket is done and please wait before merging due to I have to get a confirmation from Susanna in regard to images. I will assign you as a reviewer once I got the answer. thanks

**Comment by hoseinmirian** [comment]
image


please check the carousel as well as all the icons used in search result due to they are replaced with new SVG icons. 
image

**Review by knirirr — CHANGES_REQUESTED** [review]
The icon for "model and format" policies is missing when I look at the Netlify build.

**Comment by hoseinmirian** [comment]
> The icon for "model and format" policies is missing when I look at the Netlify build.

in fact just a change in extension fixed it. from png to svg
image

**Review by knirirr — APPROVED** [review]

**Pull request merged**
