### PR TITLE
1 hossein remove footer from search out put

### PR DESCRIPTION
**Pull request by hoseinmirian**

### CODE REVIEW

**Review by knirirr — COMMENTED** [review]
Looks like this is working.
But, I'm not certain why the footer has been removed - would you mind adding some context, please?

**Review by terazus — APPROVED** [review]

**Comment by terazus** [comment]
> 
> 
> Looks like this is working.
> But, I'm not certain why the footer has been removed - would you mind adding some context, please?

Because there's a branch to add the new footer :)

**Comment by knirirr** [comment]
> > Looks like this is working.
> > But, I'm not certain why the footer has been removed - would you mind adding some context, please?
> 
> Because there's a branch to add the new footer :)

It would be useful to have some sort of description in the comment which would explain that, though.

**Review by knirirr — APPROVED** [review]

**Review by ramGranell — APPROVED** [review]

**Comment by hoseinmirian** [comment]
> not certain why the footer has been removed - would you mind adding some context, please

Footer is not removed (it is somehow pushed out of the visibile area )is just not showing due to the layout structure which will be fixed by merging next branches into each other...

**Pull request merged**
