### PR TITLE
Add fairsharingID to how to cite

### LINKED ISSUE #1356: How to cite this record - please update text
Currently all records without a DOI have this in the "How to cite this record" box within the General Information:
how2cite
Example: https://beta.fairsharing.org/3519

And the following for records with DOIs:
how2citedoi
Example: https://beta.fairsharing.org/FAIRsharing.9kahy4

Because collections never have a DOI, we would like to update the text of "How to cite this record" so that the FAIRsharing URL is included with its FAIRsharing ID, e.g. for the Pistoia example above:

> FAIRsharing.org: Pistoia Alliance FIPs; Pistoia Alliance FAIR Implementation Profiles, URL: https://beta.fairsharing.org/3519, Last Edited: Thursday, November 11th 2021, 10:56, Last Editor: allysonlister,Last Accessed: Tuesday, November 16th 2021, 13:43 

We are happy for this change to be implemented across all record types **or** across collections only, whichever the devs prefer. Please note the low priority.

Thanks!

### PR DESCRIPTION
**Pull request by hoseinmirian**
Added FAIRsharing ID to the description of how to cite: for the test please use:
http://localhost:8080/3519
http://localhost:8080/FAIRsharing.9kahy4

### CODE REVIEW

**Review by knirirr — CHANGES_REQUESTED** [review]
Both records show NaN for the record ID:

Screenshot 2021-11-17 at 15 33 08


Screenshot 2021-11-17 at 15 33 41

I would also suggest adding @allysonlister as a reviewer on this PR.

**Comment by hoseinmirian** [comment]
@knirirr is VUE_APP_HOSTNAME defined in env var? If you note you see that the link of NAN is active. so I suspect about the getHostName is not getting the defined var. 
image


image

**Comment by hoseinmirian** [comment]
says getHostname is not defined in console
image

**Review by allysonlister — CHANGES_REQUESTED** [review]
I cannot see the "how to cite" boxes at all in this netlify build. Please let me know when I should check again. Thanks!
missing

**Comment by allysonlister** [comment]
I'm really sorry, Hossein, but I still cannot see any of the "how to cite" boxes - they are still missing from the records in https://deploy-preview-1363--fairsharing.netlify.app/

**Comment by hoseinmirian** [comment]
@knirirr 
I accurately and in different ways tested ENV var to load it but it was not successful due to the below reason:
ENV var is not defined until we merge into dev! to prove this if you take a look at the code of TermOfUse 

plz compare:
https://deploy-preview-1363--fairsharing.netlify.app/#/terms
with
https://beta.fairsharing.org/terms

you can see that the last sentence in the deploy version

 even in the terms and everywhere that any env is defined is not working:
image


so the conclusion is that if you confirm I can create a new branch and ignore the parts that ENV is not showing due to we know it will be shown.

**Comment by allysonlister** [comment]
I'm confused - am I asking to approve a change that I can't see? Or is that just a question for @knirirr ? Thanks! :-)

**Comment by knirirr** [comment]
> I'm confused - am I asking to approve a change that I can't see? Or is that just a question for @knirirr ? Thanks! :-)

This is still a draft, but you mentioned above that there was something that appeared missing to you. Are you able to supply more information about that (ideally inc. a link?).

**Comment by allysonlister** [comment]
Apologies, I thought I had been asked to re-review. I'll wait until I'm asked to review again, then look :)

**Comment by hoseinmirian** [comment]
this branch is closed and replaced with 
https://github.com/FAIRsharing/fairsharing.github.io/pull/1382

**Pull request closed without merging**
