### PR TITLE
Record page tooltips

### PR DESCRIPTION
**Pull request by knirirr**
Ticket: https://github.com/FAIRsharing/fairsharing.github.io/issues/2295

### CODE REVIEW

**Comment by knirirr** [comment]
Here's where the tooltip definition text can be found:
https://github.com/FAIRsharing/fairsharing.github.io/blob/record_tooltips_2295/src/data/recordTooltips.json

**Review by delphinedauga — APPROVED** [review]

**Comment by allysonlister** [comment]
Here is the current view on a screen-maximised version of dryad in both the netlify and prod builds. It seems that every field EXCEPT homepage, year, type and registry are all aligned differently from how they are at present.

Once the alignment is fixed I will approve. In the meantime I have also updated the tooltips slightly [here](https://github.com/FAIRsharing/fairsharing.github.io/blob/record_tooltips_2295/src/data/recordTooltips.json). Did I do that correctly? 

Thanks!

Netlify:
Screenshot from 2024-05-13 10-21-19


Prod:
image

**Comment by allysonlister** [comment]
"maintainers" has an empty tooltip - please could you add the following text for it?

"A list of developers of this resource who have claimed ownership of the record both for attribution and to perform updates the record."

**Comment by knirirr** [comment]
Your modification was successful; the application runs locally.
I have added text for maintainers.
I'm aware of the alignment but it's not within my capabilities to fix, unfortunately.

**Review by prakhyatox — APPROVED** [review]

**Review by ramGranell — COMMENTED** [review]
There are two things:
1. Content of the tooltips:
I think that the tooltip of Maintainers is missing "to", i.e.  "...perform updates to the record.". 
Maybe in the tooltip of "Taxonomic Range" it would be helpful to indicate that this field is only for "Life science related records", i.e. this is not apply to other disciplines instead the name is generic as taxonomies exist in other areas. I suppose that this field is heritage from Biosharing. Writing a thing like "This is only applied to records related to life science."?
2. When I go the icons of support, organisations, data processes it appears a blue circle with a question mark and expect to have a tooltip but nothing appears. Anyway, this may not be related to this ticket and tooltips.

**Comment by allysonlister** [comment]
I agree with Ramon on his first point.

With regards to his second point, I do not see any tooltips or grey question mark icons outside of the General Information and Cross References. However, note that in the originating ticket I said we can start with the General Information and move to the other sections after that. Given the time constraints for getting started on vue3, can I suggest that a new ticket is spawned from https://github.com/FAIRsharing/fairsharing.github.io/issues/2295#issuecomment-2085344914 that can be given a low, post-vue3 priority please?

Finally, some elements of the General Information tab are still missing "?" below is an example from https://deploy-preview-2305--fairsharing.netlify.app/3495 which shows that Contact, Organisations and Reference URL are missing "?":
Screenshot from 2024-08-29 13-52-49

Please can you carefully go through all possible fields and make sure they have them? The main issue with the screenshot above is that Reference URL is just for collections (and so may easily have been missed), and Contact and Organisation are ONLY added to the General Information when it is a Collection, because Collections don't have the subsections where these elements would normally go.

Thanks!

**Comment by knirirr** [comment]
I've added the missing sections and corrected the text.
Re. the ticket, I'd think it best to keep the existing one open and to open another PR when there's time to address other parts of the application.

**Review by allysonlister — APPROVED** [review]
thank you - the update looks good, and happy to progress with the rest of the ticket as you suggest

**Review by delphinedauga — APPROVED** [review]

**Review by ramGranell — APPROVED** [review]

**Pull request merged**
