### PR TITLE
Hossein update collection records #1323

### LINKED ISSUE #1323: Update Collections Display
Collection records are allowed to have contacts, but although such contacts are editable within the edit interface, they are not being displayed within the record view and should be.

Example: https://beta.fairsharing.org/3607 has two contacts, neither of which are shown.

As a larger issue, please could you go through all valid collection fields and find out which are not being displayed in the record view? We need to start showing anything that is allowed within the data model.

Haven't created the ticket as a bug as it may be there was some constraint when the front end was created that I was unaware of.

### PR DESCRIPTION
**Pull request by hoseinmirian**
testing a record with organisations and contacts:
http://localhost:8080/3493

testing a record without organisations and contact:
http://localhost:8080/3494

### CODE REVIEW

**Comment by allysonlister** [comment]
When I try to access https://deploy-preview-1454--fairsharing.netlify.app, it redirects me to https://deploy-preview-1454--fairsharing.netlify.app/maintenance - how do I get around this?

**Comment by hoseinmirian** [comment]
> When I try to access https://deploy-preview-1454--fairsharing.netlify.app, it redirects me to https://deploy-preview-1454--fairsharing.netlify.app/maintenance - how do I get around this?

there might be. an issue with the API that not loading data. so please give it a while and try again. tnx. I checked it now and its working.

**Comment by allysonlister** [comment]
sorry - still not working... thanks!


--

Dr. Allyson Lister

FAIRsharing Coordinator - Content & Community


Oxford e-Research Centre, University of Oxford

Data Readiness Group: https://datareadiness.eng.ox.ac.uk/


ORCiD: 0000-0002-7702-4495
@allysonlister

Please note that I work part time. If the matter is urgent, you may wish to email ***@***.******@***.***> instead.


For more on FAIRsharing, please see https://fairsharing.org

________________________________

**Comment by hoseinmirian** [comment]
@allysonlister its working for me! wondering what is your machine problem. please check the URL in the screenshot from the record with organisations and contacts included in generalInformation section

image

**Comment by hoseinmirian** [comment]
@allysonlister I have one question here:
image

we do have the ability to make an organisation lead but not a publication in the editor. can you please clarify about this statement. tnx

**Comment by allysonlister** [comment]
Here is Genbank. See that its publication is up in the General Information section as it is marked as the publication for citation. I wasn't as specific with my wording in the document, and used "lead" instead of "publication for citation". As it has caused confusion, I have now updated the specification. Thanks!

https://beta.fairsharing.org/FAIRsharing.9kahy4

**Comment by hoseinmirian** [comment]
@allysonlister @knirirr 
based on the data analysis I did there is no relationship between a fairsharing Record and. a publication that has the same name(in order to know its a lead one) cz even "GenBank" as the name of the fairsharingRecord is not the same as the publication title which is "GenBank." with an extra dot. Plus I don;t think manually asking curators to make sure names are exactly as the title of publication is not a good solution unless we automize that part or put a specific validation. I have included other solutions below as well:

image

currently the only solution I can see is to make sure the name of the fairsharing record is exactly the same as a publication's title so I can compare them in the code 

or 

define a boolean in the backend for each publication item so I know its related to the current record and do what I am asked in the gitbook which its statement screenshot was discussed in a couple of comments before..

tnx

**Comment by allysonlister** [comment]
Ok, I think I need to explain how publications work in FAIRsharing. I suggest you add this ticket to our Monday morning meeting agenda and we can talk about it on Monday. Thanks!

**Comment by hoseinmirian** [comment]
@allysonlister @knirirr you can review now. branch ready

**Review by allysonlister — CHANGES_REQUESTED** [review]
Thank you, this is looking good. However, please note the following issues:

1. https://deploy-preview-1454--fairsharing.netlify.app/3510 and https://deploy-preview-1454--fairsharing.netlify.app/3533 (and others) don't have their "How to cite this record" box at the bottom of the general information card, and all collections should have this. (Not all will have the "publication for citation" box that sometimes sits to the right of "how to cite this record). Other records, such as https://deploy-preview-1454--fairsharing.netlify.app/3499, do have the "how to cite this record" box, so I'm not sure what's different.
2. the left alignment of the contacts does not match the other items in the card (e.g. https://deploy-preview-1454--fairsharing.netlify.app/3610)
alignment
3. I apologise, I was not clear enough with regards to the organisation relationships. I forgot to tell you what to do about some of them (and "associated with" has only recently been added). I have now updated the spec document as follows: organisations with the relationship type of "maintains", "associated with" or "collaborates on" should be allowed, but no other relationship types (i.e. undefined or funds). To help with this when you are updating the code, I have added at least one of each type of organisation relationship to https://deploy-preview-1454--fairsharing.netlify.app/3610, and you can see test with this if it helps. Currently, the "associated with" isn't visible.

Once these are sorted, I will have another thorough check of collections.

Thanks!

**Review by allysonlister — CHANGES_REQUESTED** [review]
Item 2 in my previous post is not yet complete (alignment of contact list). Everything else appears to be working as intended.
Thanks!

**Comment by hoseinmirian** [comment]
> Item 2 in my previous post is not yet complete (alignment of contact list). Everything else appears to be working as intended. Thanks!

item2 is fine to me! Would you please provide screenshot of your screen screenshot from preview:
image

**Comment by allysonlister** [comment]
Sure! Here's the screenshot:
tp

**Comment by hoseinmirian** [comment]
@allysonlister please use the preview link and approve it if your ok. @knirirr please review after Ally. tnx

**Review by allysonlister — CHANGES_REQUESTED** [review]
OK - I've had a look at a variety of screen sizes and at a few records, and some of the same issues are appearing, sometimes in different fields. Please can you ensure you check a few different window sizes / browsers etc before asking for our review? Here are the current issues:

for https://deploy-preview-1454--fairsharing.netlify.app/3499:
issues


1. the ID used in the "How to cite this record" for every single collection that I have checked (e.g. https://deploy-preview-1454--fairsharing.netlify.app/3499) is, oddly, "NaN". Why is it not the URL of the record (Collections don't have DOIs)?
2. homepage and reference URL are not aligned properly on bigger window sizes

**Comment by hoseinmirian** [comment]
@knirirr thanks. for commits. 
@allysonlister ready to review.

**Comment by hoseinmirian** [comment]
@allysonlister please ignore the NAN one, I ll take care of it in another ticket. its nothing to do with this branch,; tnx

**Review by allysonlister — CHANGES_REQUESTED** [review]
Please do check the alignment in multiple browsers and windows, as there are still issues with reference URL.
align

**Review by allysonlister — CHANGES_REQUESTED** [review]
Apologies, it seems I didn't specify the contacts display. Thank you for adding some test contacts, because I had forgotten to do that and it has helped. I have updated the specification in gitbook, and it now says "if there are no contacts, the contacts field value should be "None". Contacts should be displayed in the same way maintainers are displayed, i.e. their name, with a hyperlink to their email address, with the (optional) ORCID shown via the logo after the name"

Right now, the contacts are displayed differently (from https://deploy-preview-1454--fairsharing.netlify.app/3610):
contacts

Please could they be displayed as the maintainers are, e.g. in https://deploy-preview-1454--fairsharing.netlify.app/3499 ?

Thanks!

**Comment by hoseinmirian** [comment]
@allysonlister 

please test http://localhost:8080/3610 for seeing a record with contact and /3611 for seeing None for contacts

**Review by allysonlister — CHANGES_REQUESTED** [review]
Thank you! Just one last change please; it seems the contact list is in **bold**, and maintainers are not. Please could you remove the bolding from the contacts, so that they look the same? Thanks!

**Review by allysonlister — APPROVED** [review]
thank you!

**Review by knirirr — APPROVED** [review]

**Pull request merged**
